# -*- coding: utf-8 -*-
msg = {
    'ar': {'basic-changing': u'روبوت: تغيير ...',
    },
    'cs': {'basic-changing': u'Robot změnil ...',
    },
    'de': {'basic-changing': u'Bot: Ändere ...',
    },
    'en': {'basic-changing': u'Bot: Changing ...',
    },
    'fa': {'basic-changing': u'ربات: تغییر ...',
    },
    'fr': {'basic-changing': u'Robot: Changé ...',
    },
    'ja': {'basic-changing': u'ロボットによる：編集',
    },
    'ksh': {'basic-changing': u'Bot: Änderung ...',
    },
    'nds': {'basic-changing': u'Bot: Ännern ...',
    },
    'nl': {'basic-changing': u'Bot: wijziging ...',
    },
    'pl': {'basic-changing': u'Bot: zmienia ...',
    },
    'pt': {'basic-changing': u'Bot: alterando...',
    },
    'ru': {'basic-changing': u'Бот: изменил ...',
    },
    'sv': {'basic-changing': u'Bot: Ändrar ...',
    },
    'uk': {'basic-changing': u'Бот: змінив ...',
    },
    'zh': {'basic-changing': u'機器人：編輯.....',
    },
}
