# -*- coding: utf-8 -*-
msg = {
	# Author: Naudefj
	'af': {
		'category-was-moved': u'Robot: kategorie is geskuif na [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'Robot: lys van %(fromcat) (%(num)d bladsye)',
		'category-changing': u'Robot: wysig %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategorie is opgehef',
		'category-also-in': u'(ook in %(alsocat))',
		'category-replacing': u'Robot: kategorie %(oldcat)s is vervang met %(newcat)s',
		'category-adding': u'Robot: [[Kategorie:%(newcat)s]] bygevoeg',
		'category-removing': u'Robot: verwyder uit %(oldcat)',
	},
	'ar': {
		'category-was-moved': u'روبوت: التصنيف نقل إلى [[:تصنيف:%(newcat)|%(title)s]]',
		'category-listifying': u'روبوت: عرض من %(fromcat) (%(num)d مدخلة)',
		'category-changing': u'روبوت: تغيير %(oldcat)s',
		'category-was-disbanded': u'روبوت: التصنيف تم الاستغناء عنه',
		'category-also-in': u'(ﺄﻴﺿﺍ ﻒﻳ %(alsocat))',
		'category-replacing': u'روبوت: استبدال التصنيف %(oldcat)s ب %(newcat)s',
		'category-adding': u'روبوت: إضافة [[تصنيف:%(newcat)s]]',
		'category-removing': u'روبوت: إزالة من %(oldcat)',
	},
	'bat-smg': {
		'category-was-moved': u'Robots: Kateguorėjė bova parvadėnta i [[:Kateguorėjė:%(newcat)|%(title)s]]',
		'category-adding': u'Robots: Pridedama [[Kateguorėjė:%(newcat)s]]',
		'category-removing': u'Robots: Trėnama ėš %(oldcat)',
	},
	'be-x-old': {
		'category-was-moved': u'Робат: катэгорыя перайменаваная ў [[:Катэгорыя:%(newcat)|%(title)s]]',
		'category-changing': u'Робат: зьмена %(oldcat)s',
		'category-was-disbanded': u'Робат: катэгорыя расфармаваная',
		'category-also-in': u'(таксама ў %(alsocat))',
		'category-adding': u'Робат: дадаваньне [[Катэгорыя:%(newcat)s]]',
		'category-removing': u'Робат: выключэньне з [[%(oldcat)]]',
	},
	# Author: Wikitanvir
	'bn': {
		'category-was-moved': u'বট: বিষয়শ্রেণী [[:বিষয়শ্রেণী:%(newcat)s|%(title)s]]-এ স্থানান্তরিত হয়েছে',
	},
	# Author: CERminator
	'bs': {
		'category-was-moved': u'Robot: Kategorija je premještena u [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'Bot: ispisuje iz %(fromcat) (%(num)d stavki)',
		'category-changing': u'Robot: mijenja %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategorija je raspuštena',
		'category-also-in': u'(također u %(alsocat))',
		'category-replacing': u'Robot: Mijenja kategoriju %(oldcat)s sa %(newcat)s',
		'category-adding': u'Robot: dodaje [[Category:%(newcat)s]]',
		'category-removing': u'Bot: uklanja iz %(oldcat)',
	},
	'ca': {
		'category-was-moved': u'Robot: La categoria s\'ha mogut a [[:Categoria:%(newcat)|%(title)s]]',
		'category-listifying': u'Robot: Llistant de %(fromcat) (%(num)d entrades)',
		'category-changing': u'Robot: Canviant %(oldcat)s',
		'category-was-disbanded': u'Robot: La categoria s\'ha eliminat',
		'category-also-in': u'(també a %(alsocat))',
		'category-adding': u'Robot: Afegint [[Categoria:%(newcat)s]]',
		'category-removing': u'Robot: Eliminant de %(oldcat)',
	},
	'cs': {
		'category-was-moved': u'Kategorie přesunuta na [[:Kategorie:%(newcat)|%(title)s]]',
		'category-listifying': u'Robot: vytvoření soupisu obsahu kategorie %(fromcat) (%(num)d položek)',
		'category-changing': u'Robot změnil [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-was-disbanded': u'Robot: kategorie byla vyprázdněna',
		'category-also-in': u'(také v %(alsocat))',
		'category-replacing': u'Robot nahradil kategorii %(oldcat)s za %(newcat)s',
		'category-adding': u'Robot přidal [[Kategorie:%(newcat)s]]',
		'category-removing': u'Robot: odstranění kategorie %(oldcat)',
	},
	'da': {
		'category-was-moved': u'Robot: Kategori flyttet til [[:Category:%(newcat)|%(title)s]]',
		'category-changing': u'Robot: Ændrer %(oldcat)s',
		'category-was-disbanded': u'Robot: Kategorien blev opløst',
		'category-also-in': u'(også i %(alsocat))',
		'category-adding': u'Robot: Tilføjer [[Kategori:%(newcat)s]]',
		'category-removing': u'Robot: Fjerner fra %(oldcat)',
	},
	# Author: The Evil IP address
	'de': {
		'category-was-moved': u'Bot: Kategorie wurde nach [[:Kategorie:%(newcat)|%(title)s]] verschoben',
		'category-listifying': u'Bot: Liste aus %(fromcat) (%(num)d Einträge)',
		'category-changing': u'Bot: Ändere %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategorie wurde aufgelöst',
		'category-also-in': u'(auch in %(alsocat))',
		'category-replacing': u'Bot: Ersetze Kategorie %(oldcat)s durch %(newcat)s',
		'category-adding': u'Bot: Ergänze [[Kategorie:%(newcat)s]]',
		'category-removing': u'Bot: Entferne aus %(oldcat)',
	},
	# Author: Evropi
	'el': {
		'category-was-moved': u'Bot: Η κατηγορία μετακινείθηκε στο [[:Κατηγορία:%(newcat)s|%(title)s]]',
		'category-listifying': u'Bot: Καταλογίζοντας από %(fromcat) (%(num)d entries)',
		'category-changing': u'Robot: Αλλάζοντας %(oldcat)ες',
		'category-also-in': u'(επίσης στο %(alsocat)ες)',
		'category-replacing': u'Robot: Αντικατάσταση κατηγοριών %(oldcat)ες με %(newcat)ες',
	},
	'en': {
		'category-was-moved': u'Robot: Category was moved to [[:Category:%(newcat)s|%(title)s]]',
		'category-listifying': u'Bot: Listifying from %(fromcat)s (%(num)d entries)',
		'category-changing': u'Robot: Changing %(oldcat)s',
		'category-was-disbanded': u'Bot: Category was disbanded',
		'category-also-in': u'(also in %(alsocat)s)',
		'category-replacing': u'Robot: Replacing category %(oldcat)s with %(newcat)s',
		'category-adding': u'Robot: Adding [[Category:%(newcat)s]]',
		'category-removing': u'Bot: Removing from %(oldcat)s',
	},
	'es': {
		'category-was-moved': u'Robot: La categoría ha sido movida a [[:Category:%(newcat)|%(title)s]]',
		'category-changing': u'Bot: Cambiada %(oldcat)s',
		'category-was-disbanded': u'Robot: La categoría ha sido eliminada',
		'category-also-in': u'(también en %(alsocat))',
		'category-adding': u'Bot: Añadida [[Categoría:%(newcat)s]]',
		'category-removing': u'Bot: Eliminada de la %(oldcat)',
	},
	'fa': {
		'category-was-moved': u'ربات:رده به رده  [[:رده:%(newcat)|%(title)s]] منتقل شده‌است',
		'category-listifying': u'ربات:فهرست کردن اعضای رده %(fromcat)(%(num)d عضو)',
		'category-changing': u'ربات:تغییر %(oldcat)s',
		'category-was-disbanded': u'ربات: رده خالی',
		'category-also-in': u'(ﻪﻣچﻥیﻥ ﺩﺭ %(alsocat))',
		'category-replacing': u'ربات جایگزینی رده %(oldcat)s با %(newcat)s',
		'category-adding': u'ربات: افزودن [[رده:%(newcat)s]]',
		'category-removing': u'ربات:حذف از %(oldcat)',
	},
	# Author: Crt
	'fi': {
		'category-was-moved': u'Botti siirsi luokan nimelle [[:Luokka:%(newcat)|%(title)s]]',
		'category-listifying': u'Botti listasi luokan %(fromcat) (%(num)d jäsentä)',
		'category-changing': u'Botti muutti luokan %(oldcat)s',
		'category-was-disbanded': u'Botti tyhjensi luokan',
		'category-also-in': u'(myös luokassa %(alsocat))',
		'category-replacing': u'Botti korvasi luokan %(oldcat)s luokalla %(newcat)s',
		'category-adding': u'Botti lisäsi luokkaan [[Luokka:%(newcat)s]]',
		'category-removing': u'Botti poisti luokasta %(oldcat)',
	},
	'fr': {
		'category-was-moved': u'Robot : catégorie déplacée sur [[:Category:%(newcat)|%(title)s]]',
		'category-changing': u'Robot : modifie [[%(oldcat)s]]',
		'category-also-in': u'(également dans %(alsocat))',
		'category-adding': u'Robot : ajoute [[Catégorie:%(newcat)s]]',
		'category-removing': u'Robot : Retiré depuis %(oldcat)',
	},
	# Author: Amire80
	'he': {
		'category-was-moved': u'בוט: הקטגוריה הועברה לשם [[:קטגוריה:%(newcat)|%(title)s]]',
		'category-listifying': u'בוט: יוצר רשימה מהקטגוריה %(fromcat) (%(num)d דפים)',
		'category-changing': u'בוט: משנה %(oldcat)s',
		'category-was-disbanded': u'בוט: הקטגוריה פורקה',
		'category-also-in': u'(גם בקטגוריות %(alsocat))',
		'category-replacing': u'בוט מחליף את הקטגוריה %(oldcat)s בקטגוריה %(newcat)s',
		'category-adding': u'בוט: מוסיף [[קטגוריה:%(newcat)s]]',
		'category-removing': u'בוט: מסיר את הדף מהקטגוריה %(oldcat)',
	},
	'hu': {
		'category-was-moved': u'A bot áthelyezte a kategória tartalmát ide: [[:Kategória:%(newcat)|%(title)s]]',
		'category-listifying': u'%(fromcat) listázása bottal (%(num)d lap)',
		'category-changing': u'Módosítás bottal: [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-was-disbanded': u'A bot kiürítette a kategóriát',
		'category-adding': u'[[Kategória:%(newcat)s]] hozzáadása bottal',
		'category-removing': u'[[%(oldcat)]] eltávolítása bottal',
	},
	# Author: McDutchie
	'ia': {
		'category-was-moved': u'Robot: Categoria transferite a [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'Robot: Face lista de %(fromcat) (%(num)d entratas)',
		'category-changing': u'Robot: Modification de %(oldcat)s',
		'category-was-disbanded': u'Robot: Categoria esseva dissolvite',
		'category-also-in': u'(equalmente in %(alsocat))',
		'category-replacing': u'Robot: Reimplacia categoria %(oldcat)s per %(newcat)s',
		'category-adding': u'Robot: Addition de [[Categoria:%(newcat)s]]',
		'category-removing': u'Robot: Eliminate de %(oldcat)',
	},
	# Author: IvanLanin
	'id': {
		'category-was-moved': u'Bot: Kategori dipindahkan ke [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'Bot: Membuat daftar dari %(fromcat)s (%(num)d entri)',
		'category-changing': u'Bot: Mengganti %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategori dipecah',
		'category-also-in': u'(juga dalam %(alsocat)s)',
		'category-replacing': u'Bot: Mengganti kategori %(oldcat)s dengan %(newcat)s',
		'category-adding': u'Bot: Menambahkan [[Kategori:%(newcat)s]]',
		'category-removing': u'Bot: Menghapus dari %(oldcat)s',
	},
	'is': {
		'category-changing': u'Vélmenni: Breyti flokknum [[%(oldcat)s]]',
		'category-also-in': u'(einnig í %(alsocat))',
		'category-adding': u'Vélmenni: Bæti við [[Flokkur:%(newcat)s]]',
		'category-removing': u'Vélmenni: Fjarlægi [[%(oldcat)]]',
	},
	# Author: EdoDodo
	'it': {
		'category-was-moved': u'Bot: La categoria è stata sostituita da [[:Categoria:%(newcat)|%(title)s]]',
		'category-changing': u'Bot: Modifico %(oldcat)s',
		'category-was-disbanded': u'Bot: La categoria è stata eliminata',
		'category-also-in': u'(anche in %(alsocat))',
		'category-replacing': u'Bot: Sostituzione di %(oldcat) con %(newcat)',
		'category-adding': u'Bot: Aggiungo [[Categoria:%(newcat)s]]',
		'category-removing': u'Bot: Rimozione da %(oldcat)',
	},
	'ja': {
		'category-was-moved': u'ロボットによる: カテゴリ [[:Category:%(newcat)]]へ移動',
		'category-changing': u'ロボットによる: カテゴリ変更 [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-replacing': u'ロボットによる: カテゴリ変更 [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-adding': u'ロボットによる: カテゴリ追加 [[Category:%(newcat)s]]',
		'category-removing': u'ロボットによる:[[%(oldcat)]]を除去',
	},
	'kk': {
		'category-was-moved': u'Бот: Санат [[:Санат:%(newcat)|%(title)s]] дегенге жылжытылды',
		'category-listifying': u'Бот: %(fromcat) дегеннен (%(num)d буын) тізімдеді',
		'category-changing': u'Бот: %(oldcat)s дегенді түзетті',
		'category-was-disbanded': u'Бот: Санат тарқатылды',
		'category-also-in': u'(тағы да %(alsocat) дегенде)',
		'category-adding': u'Бот: [[Санат:%(newcat)s]] үстеді',
		'category-removing': u'Бот: %(oldcat) дегеннен аластатты',
	},
	'ko': {
		'category-was-moved': u'로봇: 분류가 [[:분류:%(newcat)|%(title)s]]로 옮겨짐',
		'category-changing': u'로봇: %(oldcat)s 수정',
		'category-adding': u'로봇: [[분류:%(newcat)s]] 추가',
	},
	'ksh': {
		'category-was-moved': u'Bot: Saachjropp noh [[:Category:%(newcat)|%(title)s]] jeschovve',
		'category-changing': u'Bot: %(oldcat)s ußjewääßelt',
		'category-was-disbanded': u'Bot: de Saachjropp is nu opjelööß',
		'category-adding': u'Bot: [[Saachjropp:%(newcat)s]] erinjedonn',
		'category-removing': u'Bot: uß de %(oldcat) ußjedraare',
	},
	# Author: UV
	'la': {
		'category-was-moved': u'automaton: categoria mota est ad [[:Category:%(newcat)|%(title)s]]',
		'category-changing': u'automaton: mutans %(oldcat)s→[[%(newcat)s]]',
		'category-was-disbanded': u'automaton: categoria dissoluta est',
		'category-also-in': u'(etiam in %(alsocat))',
		'category-replacing': u'automaton: mutans categoriam %(oldcat)s→[[%(newcat)s]]',
		'category-adding': u'automaton: addens [[Categoria:%(newcat)s]]',
		'category-renamed': u'automaton: mota ex %(oldcat)s. Auctores: %(authors)s',
		'category-removing': u'automaton abdit %(oldcat)',
	},
	# Author: Robby
	'lb': {
		'category-was-moved': u'Bot: Kategorie gouf geréckelt: Nei [[:Kategorie:%(newcat)|%(title)s]]',
		'category-listifying': u'Bot: Lëscht vun der %(fromcat) (%(num)d Memberen)',
		'category-changing': u'Bot: Ännere vu(n) %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategorie gouf opgeléist',
		'category-also-in': u'(och a(n) %(alsocat))',
		'category-replacing': u'Bot: Ersetze vun der Kategorie %(oldcat)s duerch %(newcat)s',
		'category-adding': u'Bot: Derbäi setzen [[Kategorie:%(newcat)s]]',
		'category-removing': u'Bot: Ewech huele vun %(oldcat)',
	},
	'lt': {
		'category-was-moved': u'robotas: Kategorija pervadinta į [[:Category:%(newcat)|%(title)s]]',
		'category-changing': u'robotas: Keičiama %(oldcat)s',
		'category-adding': u'robotas: Pridedama [[Kategorija:%(newcat)s]]',
	},
	# Author: Bjankuloski06
	'mk': {
		'category-was-moved': u'Робот: Категоријата е преместена во [[:Категорија:%(newcat)|%(title)s]]',
		'category-listifying': u'Бот: Попишувам од %(fromcat) (%(num)d ставки)',
		'category-changing': u'Робот: Ја менувам %(oldcat)s',
		'category-was-disbanded': u'Бот: Категоријата е распуштена',
		'category-also-in': u'(и во %(alsocat))',
		'category-replacing': u'Робот: Ја заменувам категоријата %(oldcat)s со %(newcat)s',
		'category-adding': u'Робот: Додавам [[Категорија:%(newcat)s]]',
		'category-renamed': u'Робот: Преместено од %(oldcat)s. Автори: %(authors)s',
		'category-removing': u'Бот: Отстранувам од %(oldcat)',
	},
	'nds': {
		'category-was-moved': u'Kat-Bot: Kategorie na [[:Category:%(newcat)|%(title)s]] schaven',
		'category-changing': u'Kat-Bot: %(oldcat)s utwesselt',
		'category-was-disbanded': u'Kat-Bot: Kategorie is nu oplööst',
		'category-adding': u'Kat-Bot: [[Kategorie:%(newcat)s]] rin',
		'category-removing': u'Kat-Bot: rut ut %(oldcat)',
	},
	'nds-nl': {
		'category-was-moved': u'Bot: kattegerie is herneumd naor [[:Kattegerie:%(newcat)|%(title)s]]',
		'category-listifying': u'Bot: lieste van %(fromcat) (%(num)d pagina\'s)',
		'category-changing': u'bot: wieziging %(oldcat)s',
		'category-was-disbanded': u'Bot: kattegerie besteet neet meer',
		'category-also-in': u'(oek in %(alsocat))',
		'category-adding': u'bot: [[kattegerie:%(newcat)s]] derbie edaon',
		'category-removing': u'Bot: vort-ehaold uut %(oldcat)',
	},
	# Author: Siebrand
	'nl': {
		'category-was-moved': u'Robot: categorie is hernoemd naar [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'Robot: lijst van %(fromcat) (%(num)d pagina\'s)',
		'category-changing': u'Robot: wijziging %(oldcat)s',
		'category-was-disbanded': u'Robot: categorie is opgeheven',
		'category-also-in': u'(ook in %(alsocat))',
		'category-replacing': u'Robot: categorie %(oldcat)s is vervangen door %(newcat)s',
		'category-adding': u'Robot: [[Categorie:%(newcat)s]] toegevoegd',
		'category-removing': u'Robot: verwijderd uit %(oldcat)',
	},
	'nn': {
		'category-was-moved': u'robot: kategorien blei flytta til [[:Kategori:%(newcat)|%(title)s]]',
		'category-changing': u'robot: endra %(oldcat)s',
		'category-was-disbanded': u'robot: kategorien blei løyst opp',
		'category-also-in': u'(òg i %(alsocat))',
		'category-adding': u'robot: la til [[Kategori:%(newcat)s]]',
		'category-removing': u'robot: fjerna ifrå %(oldcat)',
	},
	'no': {
		'category-was-moved': u'Robot: Kategorien ble flyttet til [[:Category:%(newcat)|%(title)s]]',
		'category-changing': u'Robot: Endrer %(oldcat)s',
		'category-was-disbanded': u'Robot: Kategorien ble oppløst',
		'category-also-in': u'(også i %(alsocat))',
		'category-adding': u'Robot: Legger til [[Kategori:%(newcat)s]]',
		'category-removing': u'Robot: Fjerner ifra %(oldcat)',
	},
	'pdc': {
		'category-was-moved': u'Waddefresser: Abdeeling iss gezoge warre nooch [[:Kategorie:%(newcat)|%(title)s]].',
		'category-changing': u'Waddefresser: Abdeeling vun %(oldcat)s nooch %(newcat)s geennert',
		'category-replacing': u'Waddefresser: Abdeeling von %(oldcat)s nooch %(newcat)s geennert',
		'category-adding': u'Waddefresser: [[Kategorie:%(newcat)s]] dezu geduh',
	},
	# Author: Sp5uhe
	'pl': {
		'category-was-moved': u'Robot przenosi kategorię do [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'Robot listuje kategorię %(fromcat) (%(num)d pozycji)',
		'category-changing': u'Robot przenosi %(oldcat)s',
		'category-was-disbanded': u'Robot usuwa kategorię',
		'category-also-in': u'(również w %(alsocat))',
		'category-replacing': u'Robot zastępuje kategorię %(oldcat) przez %(newcat)',
		'category-adding': u'Robot dodaje [[Category:%(newcat)s]]',
		'category-removing': u'Robot usuwa z kategorii %(oldcat)',
	},
	'pt': {
		'category-was-moved': u'Bot: Categoria [[:Category:%(newcat)|%(title)s]] foi movida',
		'category-listifying': u'Bot: Listando de %(fromcat) (%(num)d entradas)',
		'category-changing': u'Bot: Modificando [[%(oldcat)s]]',
		'category-was-disbanded': u'Bot: Categoria foi unida',
		'category-also-in': u'(também em %(alsocat))',
		'category-adding': u'Bot: Adicionando [[Categoria:%(newcat)s]]',
		'category-removing': u'Bot: Removendo [[%(oldcat)]]',
	},
	# Author: Valhallasw
	'qqq': {
		'category-also-in': u'Translations to say that the current category is in more categories than the one we\'re coming from',
	},
	# Author: Rubin
	'ru': {
		'category-was-moved': u'Робот: категория переименована в [[:Категория:%(newcat)|%(title)s]]',
		'category-listifying': u'Робот: Составляется список из (%(num)d элементов) %(fromcat)',
		'category-changing': u'Робот: изменение %(oldcat)s',
		'category-was-disbanded': u'Робот: категория расформирована',
		'category-also-in': u'(также в %(alsocat))',
		'category-replacing': u'Робот: Замена категории %(oldcat)s на %(newcat)s',
		'category-adding': u'Робот: добавление [[Категория:%(newcat)s]]',
		'category-removing': u'Робот: исключение из %(oldcat)',
	},
	'sk': {
		'category-was-moved': u'Kategória bola presunutá na [[:Kategória:%(newcat)|%(title)s]]',
		'category-changing': u'Robot zmenil [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-replacing': u'Robot nahradil kategóriu %(oldcat)s za %(newcat)s',
		'category-adding': u'Robot pridal [[Kategória:%(newcat)s]]',
	},
	# Author: Rancher
	'sr': {
		'category-was-moved': u'Робот: категорија је премештена у [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'Робот: сврставање из %(fromcat) (%(num)d entries)',
		'category-changing': u'Робот: мењање %(oldcat)s',
		'category-was-disbanded': u'Робот: категорија је распуштена',
		'category-also-in': u'(такође у %(alsocat))',
		'category-replacing': u'Робот: мењање категорије %(oldcat)s са %(newcat)s',
		'category-adding': u'Робот: додавање [[Category:%(newcat)s]]',
		'category-removing': u'Робот: уклањање из %(oldcat)',
	},
	# Author: Rancher
	'sr-el': {
		'category-was-moved': u'Robot: kategorija je premeštena u [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'Bot: svrstavanje iz %(fromcat) (%(num)d entries)',
		'category-changing': u'Robot: menjanje %(oldcat)s',
		'category-was-disbanded': u'Bot: kategorija je raspuštena',
		'category-also-in': u'(takođe u %(alsocat))',
		'category-replacing': u'Robot: menjanje kategorije %(oldcat)s sa %(newcat)s',
		'category-adding': u'Robot: dodavanje [[Category:%(newcat)s]]',
		'category-removing': u'Bot: uklanjanje iz %(oldcat)',
	},
	# Author: Ainali
	'sv': {
		'category-was-moved': u'Robot: Kategori flyttades till [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'Robot: Skapar en lista från %(fromcat) (%(num)d)',
		'category-changing': u'Robot: Ändrar %(oldcat)s',
		'category-was-disbanded': u'Robot: Kategorin upplöstes',
		'category-also-in': u'(också i %(alsocat))',
		'category-replacing': u'Robot: Ersätter kategorin %(oldcat)s med %(newcat)s',
		'category-adding': u'Robot: Lägger till [[Kategori:%(newcat)s]]',
		'category-removing': u'Robot: Tar bort från %(oldcat)',
	},
	'szl': {
		'category-adding': u'Bot dodowo: [[Kategoria:%(newcat)s]]',
	},
	# Author: Joseph
	'tr': {
		'category-was-moved': u'Robot: Kategori şuraya taşındı [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'Bot: Şuradan itibaren listeleniyor %(fromcat) (%(num)d girdi)',
		'category-changing': u'Robot: %(oldcat)s değiştiriliyor',
	},
	'uk': {
		'category-was-moved': u'Робот: категорію перейменовано на [[Категорія:%(newcat)|%(title)s]]',
		'category-changing': u'Робот: зміна %(oldcat)s',
		'category-was-disbanded': u'Робот: категорія розформована',
		'category-also-in': u'(також у %(alsocat))',
		'category-replacing': u'Робот: заміна категорії %(oldcat)s на %(newcat)s',
		'category-adding': u'Робот: додавання [[Категорія:%(newcat)s]]',
		'category-removing': u'Робот: видалення з %(oldcat)',
	},
	# Author: Minh Nguyen
	'vi': {
		'category-was-moved': u'Rôbốt: Di chuyển thể loại qua [[:Thể loại:%(newcat)|%(title)s]]',
		'category-listifying': u'Rôbốt: Danh sách hóa từ %(fromcat) (%(num)d trang)',
		'category-changing': u'Rôbốt: Thay đổi %(oldcat)s',
		'category-was-disbanded': u'Rôbốt: Thể loại bị giải tán',
		'category-also-in': u'(cũng trong %(alsocat))',
		'category-replacing': u'Rôbốt: Thay thể loại %(oldcat)s bằng %(newcat)s',
		'category-adding': u'Rôbốt: Thêm [[Thể loại:%(newcat)s]]',
		'category-renamed': u'Rôbốt: Di chuyển từ %(oldcat)s. Tác giả: %(authors)s',
		'category-removing': u'Rôbốt: Dời khỏi %(oldcat)',
	},
	'vo': {
		'category-adding': u'Bot: läükon: [[Klad:%(newcat)s]]',
	},
	'zh': {
		'category-was-moved': u'機器人:移動目錄至 [[:Category:%(newcat)|%(title)s]]',
		'category-listifying': u'機器人: 從%(fromcat)提取列表(%(num)d個項目)',
		'category-changing': u'機器人:變更目錄 [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-was-disbanded': u'機器人:本目錄已解散',
		'category-also-in': u'(也在 %(alsocat))',
		'category-replacing': u'機器人:變更目錄 [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-adding': u'機器人:新增目錄 [[Category:%(newcat)s]]',
		'category-removing': u'機器人:移除目錄 [[%(oldcat)]]',
	},
	# Author: Hydra
	'zh-hans': {
		'category-was-moved': u'机器人： 类别移动到 [[:Category:%(newcat)|%(title)]]',
	},
}