# -*- coding: utf-8 -*-
msg = {
	# Author: Naudefj
	'af': {
		'category-was-moved': u'Robot: kategorie is geskuif na [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(ook in %(alsocat)s)',
		'category-changing': u'Robot: wysig %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategorie is opgehef',
		'category-listifying': u'Robot: lys van %(fromcat)s (%(num)d bladsye)',
		'category-replacing': u'Robot: kategorie %(oldcat)s is vervang met %(newcat)s',
		'category-adding': u'Robot: [[Kategorie:%(newcat)s]] bygevoeg',
		'category-removing': u'Robot: verwyder uit %(oldcat)s',
	},
	# Author: Meno25
	'ar': {
		'category-was-moved': u'روبوت: التصنيف نقل إلى [[:تصنيف:%(newcat)s|%(title)s]]',
		'category-also-in': u'(أيضا في %(alsocat)s)',
		'category-changing': u'روبوت: تغيير %(oldcat)s',
		'category-was-disbanded': u'بوت: التصنيف تم الاستغناء عنه',
		'category-listifying': u'بوت: عرض من %(fromcat)s (%(num)d مدخلة)',
		'category-replacing': u'روبوت: استبدال التصنيف %(oldcat)s ب %(newcat)s',
		'category-adding': u'روبوت: إضافة [[تصنيف:%(newcat)s]]',
		'category-removing': u'بوت: إزالة من %(oldcat)s',
	},
	# Author: PPerviz
	'az': {
		'category-was-moved': u'Robot: Kateqoriya köçürüldü: [[:Category:%(newcat)s|%(title)s]]',
		'category-changing': u'Robot: %(oldcat)s dəyişdirildi',
		'category-was-disbanded': u'Bot: Kateqoriya ləğv edildi',
		'category-replacing': u'Robot: %(oldcat)s kateqoriyasının %(newcat)s ilə əvəzlənməsi',
		'category-adding': u'Robot: [[Kateqoriya:%(newcat)s]] əlavəsı',
	},
	# Author: Xqt
	'bar': {
		'category-changing': u'Bot: %(oldcat)s obàsst',
		'category-adding': u'Bot: Aini [[Kategorie:%(newcat)s]]',
	},
	'bat-smg': {
		'category-was-moved': u'Robots: Kateguorėjė bova parvadėnta i [[:Kateguorėjė:%(newcat)s|%(title)s]]',
		'category-adding': u'Robots: Pridedama [[Kateguorėjė:%(newcat)s]]',
		'category-removing': u'Robots: Trėnama ėš %(oldcat)s',
	},
	# Author: EugeneZelenko
	# Author: Jim-by
	'be-tarask': {
		'category-was-moved': u'Робат: катэгорыя перанесеная ў [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(таксама ў %(alsocat)s)',
		'category-changing': u'Робат: зьмена %(oldcat)s',
		'category-was-disbanded': u'Робат: катэгорыя была расфарміраваная',
		'category-listifying': u'Робат: ствараецца сьпіс з %(fromcat)s (%(num)d элемэнтаў)',
		'category-replacing': u'Робат: замена катэгорыі %(oldcat)s на %(newcat)s',
		'category-adding': u'Робат: дададзеная [[Category:%(newcat)s]]',
		'category-removing': u'Робат: выдаленьне з %(oldcat)s',
	},
	'be-x-old': {
		'category-was-moved': u'Робат: катэгорыя перайменаваная ў [[:Катэгорыя:%(newcat)s|%(title)s]]',
		'category-also-in': u'(таксама ў %(alsocat)s)',
		'category-changing': u'Робат: зьмена %(oldcat)s',
		'category-was-disbanded': u'Робат: катэгорыя расфармаваная',
		'category-adding': u'Робат: дадаваньне [[Катэгорыя:%(newcat)s]]',
		'category-removing': u'Робат: выключэньне з [[%(oldcat)s]]',
	},
	# Author: Wikitanvir
	'bn': {
		'category-was-moved': u'বট: বিষয়শ্রেণী [[:বিষয়শ্রেণী:%(newcat)s|%(title)s]]-এ স্থানান্তরিত হয়েছে',
	},
	# Author: Fulup
	'br': {
		'category-was-moved': u'Robot : Rummad dilec\'hiet da [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(ivez e %(alsocat)s)',
		'category-changing': u'Robot : O kemmañ %(oldcat)s',
		'category-was-disbanded': u'Robot : Dilamet eo bet ar rummad',
		'category-listifying': u'Robot : Roll eus %(fromcat)s (%(num)d pajenn)',
		'category-replacing': u'Robot : Oc\'h erlec\'hiañ ar rummad %(oldcat)s gant %(newcat)s',
		'category-adding': u'Robot : Oc\'h ouzhpennañ [[Rummad:%(newcat)s]]',
		'category-removing': u'Robot : Tennet diwar %(oldcat)s',
	},
	# Author: CERminator
	'bs': {
		'category-was-moved': u'Robot: Kategorija je premještena u [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(također u %(alsocat)s)',
		'category-changing': u'Robot: mijenja %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategorija je raspuštena',
		'category-listifying': u'Bot: ispisuje iz %(fromcat)s (%(num)d stavki)',
		'category-replacing': u'Robot: Mijenja kategoriju %(oldcat)s sa %(newcat)s',
		'category-adding': u'Robot: dodaje [[Category:%(newcat)s]]',
		'category-removing': u'Bot: uklanja iz %(oldcat)s',
	},
	'ca': {
		'category-was-moved': u'Robot: La categoria s\'ha mogut a [[:Categoria:%(newcat)s|%(title)s]]',
		'category-also-in': u'(també a %(alsocat)s)',
		'category-changing': u'Robot: Canviant %(oldcat)s',
		'category-was-disbanded': u'Robot: La categoria s\'ha eliminat',
		'category-listifying': u'Robot: Llistant de %(fromcat)s (%(num)d entrades)',
		'category-adding': u'Robot: Afegint [[Categoria:%(newcat)s]]',
		'category-removing': u'Robot: Eliminant de %(oldcat)s',
	},
	'cs': {
		'category-was-moved': u'Kategorie přesunuta na [[:Kategorie:%(newcat)s|%(title)s]]',
		'category-also-in': u'(také v %(alsocat)s)',
		'category-changing': u'Robot změnil [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-was-disbanded': u'Robot: kategorie byla vyprázdněna',
		'category-listifying': u'Robot: vytvoření soupisu obsahu kategorie %(fromcat)s (%(num)d položek)',
		'category-replacing': u'Robot nahradil kategorii %(oldcat)s za %(newcat)s',
		'category-adding': u'Robot přidal [[Kategorie:%(newcat)s]]',
		'category-removing': u'Robot: odstranění kategorie %(oldcat)s',
	},
	'da': {
		'category-was-moved': u'Robot: Kategori flyttet til [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(også i %(alsocat)s)',
		'category-changing': u'Robot: Ændrer %(oldcat)s',
		'category-was-disbanded': u'Robot: Kategorien blev opløst',
		'category-adding': u'Robot: Tilføjer [[Kategori:%(newcat)s]]',
		'category-removing': u'Robot: Fjerner fra %(oldcat)s',
	},
	# Author: The Evil IP address
	'de': {
		'category-was-moved': u'Bot: Kategorie wurde nach [[:Kategorie:%(newcat)s|%(title)s]] verschoben',
		'category-also-in': u'(auch in %(alsocat)s)',
		'category-changing': u'Bot: Ändere %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategorie wurde aufgelöst',
		'category-listifying': u'Bot: Liste aus %(fromcat)s (%(num)d Einträge)',
		'category-replacing': u'Bot: Ersetze Kategorie %(oldcat)s durch %(newcat)s',
		'category-adding': u'Bot: Ergänze [[Kategorie:%(newcat)s]]',
		'category-removing': u'Bot: Entferne aus %(oldcat)s',
	},
	# Author: Evropi
	# Author: Xqt
	'el': {
		'category-was-moved': u'Bot: Η κατηγορία μετακινείθηκε στο [[:Κατηγορία:%(newcat)s|%(title)s]]',
		'category-also-in': u'(επίσης στο %(alsocat)ες)',
		'category-changing': u'Robot: Αλλάζοντας %(oldcat)sες',
		'category-listifying': u'Bot: Καταλογίζοντας από %(fromcat)s (%(num)d entries)',
		'category-replacing': u'Robot: Αντικατάσταση κατηγοριών %(oldcat)ες με %(newcat)ες',
	},
	'en': {
		'category-was-moved': u'Robot: Category was moved to [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(also in %(alsocat)s)',
		'category-changing': u'Robot: Changing %(oldcat)s',
		'category-was-disbanded': u'Bot: Category was disbanded',
		'category-listifying': u'Bot: Listifying from %(fromcat)s (%(num)d entries)',
		'category-replacing': u'Robot: Replacing category %(oldcat)s with %(newcat)s',
		'category-adding': u'Robot: Adding [[Category:%(newcat)s]]',
		'category-removing': u'Bot: Removing from %(oldcat)s',
	},
	# Author: Mihxil
	'eo': {
		'category-was-moved': u'Roboto: Kategorio estas movita al [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(ankaŭ en  %(alsocat)s)',
		'category-changing': u'Roboto: ŝanĝo de %(oldcat)s',
		'category-was-disbanded': u'Roboto: kategorio estas nuligita',
		'category-listifying': u'Roboto: listo de %(fromcat)s (%(num)d da objektoj)',
		'category-replacing': u'Roboto: anstataŭigis %(oldcat)s per $(newcat)s',
		'category-adding': u'Robot: Aldonis [[Kategorion:%(newcat)s]]',
		'category-removing': u'Roboto: Forigis el %(oldcat)s',
	},
	'es': {
		'category-was-moved': u'Robot: La categoría ha sido movida a [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(también en %(alsocat)s)',
		'category-changing': u'Bot: Cambiada %(oldcat)s',
		'category-was-disbanded': u'Robot: La categoría ha sido eliminada',
		'category-adding': u'Bot: Añadida [[Categoría:%(newcat)s]]',
		'category-removing': u'Bot: Eliminada de la %(oldcat)s',
	},
	'fa': {
		'category-was-moved': u'ربات:رده به رده  [[:رده:%(newcat)s|%(title)s]] منتقل شده‌است',
		'category-also-in': u'(ﻪﻣچﻥیﻥ ﺩﺭ %(alsocat)s)',
		'category-changing': u'ربات:تغییر %(oldcat)s',
		'category-was-disbanded': u'ربات: رده خالی',
		'category-listifying': u'ربات:فهرست کردن اعضای رده %(fromcat)(%(num)d عضو)',
		'category-replacing': u'ربات جایگزینی رده %(oldcat)s با %(newcat)s',
		'category-adding': u'ربات: افزودن [[رده:%(newcat)s]]',
		'category-removing': u'ربات:حذف از %(oldcat)s',
	},
	# Author: Crt
	'fi': {
		'category-was-moved': u'Botti siirsi luokan nimelle [[:Luokka:%(newcat)s|%(title)s]]',
		'category-also-in': u'(myös luokassa %(alsocat)s)',
		'category-changing': u'Botti muutti luokan %(oldcat)s',
		'category-was-disbanded': u'Botti tyhjensi luokan',
		'category-listifying': u'Botti listasi luokan %(fromcat)s (%(num)d jäsentä)',
		'category-replacing': u'Botti korvasi luokan %(oldcat)s luokalla %(newcat)s',
		'category-adding': u'Botti lisäsi luokkaan [[Luokka:%(newcat)s]]',
		'category-removing': u'Botti poisti luokasta %(oldcat)s',
	},
	'fr': {
		'category-was-moved': u'Robot : catégorie déplacée sur [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(également dans %(alsocat)s)',
		'category-changing': u'Robot : modifie [[%(oldcat)s]]',
		'category-adding': u'Robot : ajoute [[Catégorie:%(newcat)s]]',
		'category-removing': u'Robot : Retiré depuis %(oldcat)s',
	},
	# Author: Toliño
	'gl': {
		'category-was-moved': u'Bot: A categoría trasladouse a [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(tamén en %(alsocat)s)',
		'category-changing': u'Bot: Cambio %(oldcat)s',
		'category-was-disbanded': u'Bot: A categoría foi eliminada',
		'category-listifying': u'Bot: Listando a partir de %(fromcat)s (%(num)d entradas)',
		'category-replacing': u'Bot: Substitución da categoría %(oldcat)s pola %(newcat)s',
		'category-adding': u'Bot: Engado [[Category:%(newcat)s]]',
		'category-removing': u'Bot: Elimino desde %(oldcat)s',
	},
	# Author: Amire80
	'he': {
		'category-was-moved': u'בוט: הקטגוריה הועברה לשם [[:קטגוריה:%(newcat)s|%(title)s]]',
		'category-also-in': u'(גם בקטגוריות %(alsocat)s)',
		'category-changing': u'בוט: משנה %(oldcat)s',
		'category-was-disbanded': u'בוט: הקטגוריה פורקה',
		'category-listifying': u'בוט: יוצר רשימה מהקטגוריה %(fromcat)s (%(num)d דפים)',
		'category-replacing': u'בוט מחליף את הקטגוריה %(oldcat)s בקטגוריה %(newcat)s',
		'category-adding': u'בוט: מוסיף [[קטגוריה:%(newcat)s]]',
		'category-removing': u'בוט: מסיר את הדף מהקטגוריה %(oldcat)s',
	},
	# Author: Dani
	'hu': {
		'category-was-moved': u'A bot áthelyezte a kategória tartalmát ide: [[:Kategória:%(newcat)s|%(title)s]]',
		'category-also-in': u'(a következőkben is: %(alsocat)s)',
		'category-changing': u'Módosítás bottal: [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-was-disbanded': u'A bot kiürítette a kategóriát',
		'category-listifying': u'%(fromcat)s listázása bottal (%(num)d lap)',
		'category-replacing': u'Bot: következő kategória cseréje: %(oldcat)s erre: %(newcat)s',
		'category-adding': u'[[Kategória:%(newcat)s]] hozzáadása bottal',
		'category-removing': u'[[%(oldcat)s]] eltávolítása bottal',
	},
	# Author: McDutchie
	'ia': {
		'category-was-moved': u'Robot: Categoria transferite a [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(equalmente in %(alsocat)s)',
		'category-changing': u'Robot: Modification de %(oldcat)s',
		'category-was-disbanded': u'Robot: Categoria esseva dissolvite',
		'category-listifying': u'Robot: Face lista de %(fromcat)s (%(num)d entratas)',
		'category-replacing': u'Robot: Reimplacia categoria %(oldcat)s per %(newcat)s',
		'category-adding': u'Robot: Addition de [[Categoria:%(newcat)s]]',
		'category-removing': u'Robot: Eliminate de %(oldcat)s',
	},
	# Author: IvanLanin
	'id': {
		'category-was-moved': u'Bot: Kategori dipindahkan ke [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(juga dalam %(alsocat)s)',
		'category-changing': u'Bot: Mengganti %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategori dipecah',
		'category-listifying': u'Bot: Membuat daftar dari %(fromcat)s (%(num)d entri)',
		'category-replacing': u'Bot: Mengganti kategori %(oldcat)s dengan %(newcat)s',
		'category-adding': u'Bot: Menambahkan [[Kategori:%(newcat)s]]',
		'category-removing': u'Bot: Menghapus dari %(oldcat)s',
	},
	'is': {
		'category-also-in': u'(einnig í %(alsocat)s)',
		'category-changing': u'Vélmenni: Breyti flokknum [[%(oldcat)s]]',
		'category-adding': u'Vélmenni: Bæti við [[Flokkur:%(newcat)s]]',
		'category-removing': u'Vélmenni: Fjarlægi [[%(oldcat)s]]',
	},
	# Author: EdoDodo
	# Author: Beta16
	'it': {
		'category-was-moved': u'Bot: La categoria è stata sostituita da [[:Categoria:%(newcat)s|%(title)s]]',
		'category-also-in': u'(anche in %(alsocat)s)',
		'category-changing': u'Bot: Modifico %(oldcat)s',
		'category-was-disbanded': u'Bot: La categoria è stata eliminata',
		'category-listifying': u'Bot: Lista del contento dalla %(fromcat)s (%(num)d pagine)',
		'category-replacing': u'Bot: Sostituzione di %(oldcat) con %(newcat)',
		'category-adding': u'Bot: Aggiungo [[Categoria:%(newcat)s]]',
		'category-removing': u'Bot: Rimozione da %(oldcat)s',
	},
	'ja': {
		'category-was-moved': u'ロボットによる: カテゴリ [[:Category:%(newcat)]]へ移動',
		'category-changing': u'ロボットによる: カテゴリ変更 [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-replacing': u'ロボットによる: カテゴリ変更 [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-adding': u'ロボットによる: カテゴリ追加 [[Category:%(newcat)s]]',
		'category-removing': u'ロボットによる:[[%(oldcat)s]]を除去',
	},
	'kk': {
		'category-was-moved': u'Бот: Санат [[:Санат:%(newcat)s|%(title)s]] дегенге жылжытылды',
		'category-also-in': u'(тағы да %(alsocat) дегенде)',
		'category-changing': u'Бот: %(oldcat)s дегенді түзетті',
		'category-was-disbanded': u'Бот: Санат тарқатылды',
		'category-listifying': u'Бот: %(fromcat)s дегеннен (%(num)d буын) тізімдеді',
		'category-adding': u'Бот: [[Санат:%(newcat)s]] үстеді',
		'category-removing': u'Бот: %(oldcat) дегеннен аластатты',
	},
	'ko': {
		'category-was-moved': u'로봇: 분류가 [[:분류:%(newcat)s|%(title)s]]로 옮겨짐',
		'category-changing': u'로봇: %(oldcat)s 수정',
		'category-adding': u'로봇: [[분류:%(newcat)s]] 추가',
	},
	# Author: Purodha
	'ksh': {
		'category-was-moved': u'Bot: Saachjropp noh [[:Category:%(newcat)s|%(title)s]] jeschovve',
		'category-also-in': u'(och en dä %(alsocat)s)',
		'category-changing': u'Bot: %(oldcat)s ußjewääßelt',
		'category-was-disbanded': u'Bot: de Saachjropp is nu opjelööß',
		'category-listifying': u'Bot: Leß vun dä %(fromcat)s (%(num)d Enndrääsch)',
		'category-replacing': u'Bot: [[%(oldcat)s]] jääje [[%(newcat)s]] ußjetuusch.',
		'category-adding': u'Bot: [[Saachjropp:%(newcat)s]] erinjedonn',
		'category-removing': u'Bot: uß de %(oldcat) ußjedraare',
	},
	# Author: UV
	'la': {
		'category-was-moved': u'automaton: categoria mota est ad [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(etiam in %(alsocat)s)',
		'category-changing': u'automaton: mutans %(oldcat)s→[[%(newcat)s]]',
		'category-was-disbanded': u'automaton: categoria dissoluta est',
		'category-replacing': u'automaton: mutans categoriam %(oldcat)s→[[%(newcat)s]]',
		'category-adding': u'automaton: addens [[Categoria:%(newcat)s]]',
		'category-removing': u'automaton abdit %(oldcat)s',
	},
	# Author: Robby
	'lb': {
		'category-was-moved': u'Bot: Kategorie gouf geréckelt: Nei [[:Kategorie:%(newcat)s|%(title)s]]',
		'category-also-in': u'(och a(n) %(alsocat)s)',
		'category-changing': u'Bot: Ännere vu(n) %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategorie gouf opgeléist',
		'category-listifying': u'Bot: Lëscht vun der %(fromcat)s (%(num)d Memberen)',
		'category-replacing': u'Bot: Ersetze vun der Kategorie %(oldcat)s duerch %(newcat)s',
		'category-adding': u'Bot: Derbäi setzen [[Kategorie:%(newcat)s]]',
		'category-removing': u'Bot: Ewech huele vun %(oldcat)s',
	},
	'lt': {
		'category-was-moved': u'robotas: Kategorija pervadinta į [[:Category:%(newcat)s|%(title)s]]',
		'category-changing': u'robotas: Keičiama %(oldcat)s',
		'category-adding': u'robotas: Pridedama [[Kategorija:%(newcat)s]]',
	},
	# Author: Bjankuloski06
	'mk': {
		'category-was-moved': u'Робот: Категоријата е преместена во [[:Категорија:%(newcat)s|%(title)s]]',
		'category-also-in': u'(и во %(alsocat)s)',
		'category-changing': u'Робот: Ја менувам %(oldcat)s',
		'category-was-disbanded': u'Бот: Категоријата е распуштена',
		'category-listifying': u'Бот: Попишувам од %(fromcat)s (%(num)d ставки)',
		'category-replacing': u'Робот: Ја заменувам категоријата %(oldcat)s со %(newcat)s',
		'category-adding': u'Робот: Додавам [[Категорија:%(newcat)s]]',
		'category-removing': u'Бот: Отстранувам од %(oldcat)s',
	},
	'nds': {
		'category-was-moved': u'Kat-Bot: Kategorie na [[:Category:%(newcat)s|%(title)s]] schaven',
		'category-changing': u'Kat-Bot: %(oldcat)s utwesselt',
		'category-was-disbanded': u'Kat-Bot: Kategorie is nu oplööst',
		'category-adding': u'Kat-Bot: [[Kategorie:%(newcat)s]] rin',
		'category-removing': u'Kat-Bot: rut ut %(oldcat)s',
	},
	'nds-nl': {
		'category-was-moved': u'Bot: kattegerie is herneumd naor [[:Kattegerie:%(newcat)s|%(title)s]]',
		'category-also-in': u'(oek in %(alsocat)s)',
		'category-changing': u'bot: wieziging %(oldcat)s',
		'category-was-disbanded': u'Bot: kattegerie besteet neet meer',
		'category-listifying': u'Bot: lieste van %(fromcat)s (%(num)d pagina\'s)',
		'category-adding': u'bot: [[kattegerie:%(newcat)s]] derbie edaon',
		'category-removing': u'Bot: vort-ehaold uut %(oldcat)s',
	},
	# Author: Siebrand
	'nl': {
		'category-was-moved': u'Robot: categorie is hernoemd naar [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(ook in %(alsocat)s)',
		'category-changing': u'Robot: wijziging %(oldcat)s',
		'category-was-disbanded': u'Robot: categorie is opgeheven',
		'category-listifying': u'Robot: lijst van %(fromcat)s (%(num)d pagina\'s)',
		'category-replacing': u'Robot: categorie %(oldcat)s is vervangen door %(newcat)s',
		'category-adding': u'Robot: [[Categorie:%(newcat)s]] toegevoegd',
		'category-removing': u'Robot: verwijderd uit %(oldcat)s',
	},
	'nn': {
		'category-was-moved': u'robot: kategorien blei flytta til [[:Kategori:%(newcat)s|%(title)s]]',
		'category-also-in': u'(òg i %(alsocat)s)',
		'category-changing': u'robot: endra %(oldcat)s',
		'category-was-disbanded': u'robot: kategorien blei løyst opp',
		'category-adding': u'robot: la til [[Kategori:%(newcat)s]]',
		'category-removing': u'robot: fjerna ifrå %(oldcat)s',
	},
	# Author: Jon Harald Søby
	'no': {
		'category-was-moved': u'Robot: Kategorien ble flyttet til [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(også i %(alsocat)s)',
		'category-changing': u'Robot: Endrer %(oldcat)s',
		'category-was-disbanded': u'Robot: Kategorien ble oppløst',
		'category-listifying': u'robot: Gjør om kategorien %(fromcat)s til liste (%(num)d elementer)',
		'category-replacing': u'robot: Erstatter kategorien %(oldcat)s med %(newcat)s',
		'category-adding': u'Robot: Legger til [[Kategori:%(newcat)s]]',
		'category-removing': u'Robot: Fjerner ifra %(oldcat)s',
	},
	# Author: Xqt
	'pdc': {
		'category-was-moved': u'Waddefresser: Abdeeling iss gezoge warre nooch [[:Kategorie:%(newcat)s|%(title)s]].',
		'category-also-in': u'(aach in %(alsocat)s)',
		'category-changing': u'Waddefresser: Abdeeling vun %(oldcat)s nooch %(newcat)s geennert',
		'category-was-disbanded': u'Waddefresser: Abdeeling iss glescht warre',
		'category-listifying': u'Waddefresser: Lischt vun %(fromcat)s (%(num)d Eitraeg)',
		'category-replacing': u'Waddefresser: Abdeeling von %(oldcat)s nooch %(newcat)s geennert',
		'category-adding': u'Waddefresser: [[Kategorie:%(newcat)s]] dezu geduh',
		'category-removing': u'Waddefresser: Aus %(oldcat)s raus gnumme',
	},
	# Author: Xqt
	'pfl': {
		'category-changing': u'Bot: %(oldcat)s gä\'ännat',
		'category-adding': u'Bot: [[Kategorie:%(newcat)s]] aigfiecht',
		'category-removing': u'Bot: Aus %(oldcat)s rausgenumme',
	},
	# Author: Sp5uhe
	'pl': {
		'category-was-moved': u'Robot przenosi kategorię do [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(również w %(alsocat)s)',
		'category-changing': u'Robot przenosi %(oldcat)s',
		'category-was-disbanded': u'Robot usuwa kategorię',
		'category-listifying': u'Robot listuje kategorię %(fromcat)s (%(num)d pozycji)',
		'category-replacing': u'Robot zastępuje kategorię %(oldcat) przez %(newcat)',
		'category-adding': u'Robot dodaje [[Category:%(newcat)s]]',
		'category-removing': u'Robot usuwa z kategorii %(oldcat)s',
	},
	# Author: Hamilton Abreu
	'pt': {
		'category-was-moved': u'Robô: A categoria foi movida para [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(também em %(alsocat)s)',
		'category-changing': u'Robô: A modificar %(oldcat)s',
		'category-was-disbanded': u'Robô: A categoria foi eliminada',
		'category-listifying': u'Robô: A listar a partir de %(fromcat)s (%(num)d entradas)',
		'category-replacing': u'Robô: A substituir a categoria %(oldcat)s por %(newcat)s',
		'category-adding': u'Robô: A adicionar [[Categoria:%(newcat)s]]',
		'category-removing': u'Robô: A remover de [[%(oldcat)s]]',
	},
	# Author: Hamilton Abreu
	'pt-br': {
		'category-was-moved': u'!!FUZZY!!Bot: Categoria [[:Category:%(newcat)s|%(title)s]] foi movida',
		'category-also-in': u'(também em %(alsocat)s)',
		'category-changing': u'!!FUZZY!!Bot: Modificando [[%(oldcat)s]]',
		'category-was-disbanded': u'!!FUZZY!!Bot: Categoria foi unida',
		'category-listifying': u'Bot: Listando de %(fromcat)s (%(num)d entradas)',
		'category-adding': u'Bot: Adicionando [[Categoria:%(newcat)s]]',
		'category-removing': u'Bot: Removendo [[%(oldcat)s]]',
	},
	# Author: Valhallasw
	# Author: Xqt
	'qqq': {
		'category-also-in': u'Translations to say that the current category is in more categories than the one we\'re coming from',
		'category-changing': u'Edit summary when the bot move pages from one category to another. %(oldcat)s is the source category, %(newcat)s the target.',
	},
	# Author: Minisarm
	'ro': {
		'category-was-moved': u'Robot: Categoria a fost mutată la [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(de asemenea în %(alsocat)s)',
		'category-changing': u'Robot: Schimbat %(oldcat)s',
		'category-was-disbanded': u'Robot: Categoria a fost desființată',
		'category-replacing': u'Robot: Înlocuit categoria %(oldcat)s cu %(newcat)s',
		'category-adding': u'Robot: Adăugat [[Category:%(newcat)s]]',
		'category-removing': u'Robot: Înlăturat din %(oldcat)s',
	},
	# Author: Rubin
	'ru': {
		'category-was-moved': u'Робот: категория переименована в [[:Категория:%(newcat)s|%(title)s]]',
		'category-also-in': u'(также в %(alsocat)s)',
		'category-changing': u'Робот: изменение %(oldcat)s',
		'category-was-disbanded': u'Робот: категория расформирована',
		'category-listifying': u'Робот: Составляется список из (%(num)d элементов) %(fromcat)',
		'category-replacing': u'Робот: Замена категории %(oldcat)s на %(newcat)s',
		'category-adding': u'Робот: добавление [[Категория:%(newcat)s]]',
		'category-removing': u'Робот: исключение из %(oldcat)s',
	},
	'sk': {
		'category-was-moved': u'Kategória bola presunutá na [[:Kategória:%(newcat)s|%(title)s]]',
		'category-changing': u'Robot zmenil [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-replacing': u'Robot nahradil kategóriu %(oldcat)s za %(newcat)s',
		'category-adding': u'Robot pridal [[Kategória:%(newcat)s]]',
	},
	# Author: Dbc334
	'sl': {
		'category-was-moved': u'Robot: Kategorija je bila prestavljena na [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(tudi v %(alsocat)s)',
		'category-changing': u'Robot: Spreminjanje %(oldcat)s',
		'category-was-disbanded': u'Bot: Kategorija je bila razpuščena',
		'category-listifying': u'Bot: Poseznamljanje iz %(fromcat)s (%(num)d vnosov)',
		'category-replacing': u'Robot: Zamenjava kategorije %(oldcat)s z/s %(newcat)s',
		'category-adding': u'Robot: Dodajanje [[Kategorija:%(newcat)s]]',
		'category-removing': u'Bot: Odstranjevanje iz %(oldcat)s',
	},
	# Author: Rancher
	'sr': {
		'category-was-moved': u'Робот: категорија је премештена у [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(такође у %(alsocat)s)',
		'category-changing': u'Робот: мењање %(oldcat)s',
		'category-was-disbanded': u'Робот: категорија је распуштена',
		'category-listifying': u'Робот: сврставање из %(fromcat)s (%(num)d entries)',
		'category-replacing': u'Робот: мењање категорије %(oldcat)s са %(newcat)s',
		'category-adding': u'Робот: додавање [[Category:%(newcat)s]]',
		'category-removing': u'Робот: уклањање из %(oldcat)s',
	},
	# Author: Rancher
	'sr-ec': {
		'category-was-moved': u'Робот: категорија је премештена у [[:Category:%(newcat)|%(title)s]]',
		'category-also-in': u'(такође у %(alsocat))',
		'category-changing': u'Робот: мењање %(oldcat)s',
		'category-was-disbanded': u'Бот: категорија је распуштена',
		'category-listifying': u'Бот: сврставање из %(fromcat) (%(num)d entries)',
		'category-replacing': u'Робот: мењање категорије %(oldcat)s са %(newcat)s',
		'category-adding': u'Робот: додавање [[Category:%(newcat)s]]',
		'category-removing': u'Бот: уклањање из %(oldcat)',
	},
	# Author: Rancher
	'sr-el': {
		'category-was-moved': u'Robot: kategorija je premeštena u [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(takođe u %(alsocat)s)',
		'category-changing': u'Robot: menjanje %(oldcat)s',
		'category-was-disbanded': u'Bot: kategorija je raspuštena',
		'category-listifying': u'Bot: svrstavanje iz %(fromcat)s (%(num)d entries)',
		'category-replacing': u'Robot: menjanje kategorije %(oldcat)s sa %(newcat)s',
		'category-adding': u'Robot: dodavanje [[Category:%(newcat)s]]',
		'category-removing': u'Bot: uklanjanje iz %(oldcat)s',
	},
	# Author: Ainali
	'sv': {
		'category-was-moved': u'Robot: Kategori flyttades till [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(också i %(alsocat)s)',
		'category-changing': u'Robot: Ändrar %(oldcat)s',
		'category-was-disbanded': u'Robot: Kategorin upplöstes',
		'category-listifying': u'Robot: Skapar en lista från %(fromcat)s (%(num)d)',
		'category-replacing': u'Robot: Ersätter kategorin %(oldcat)s med %(newcat)s',
		'category-adding': u'Robot: Lägger till [[Kategori:%(newcat)s]]',
		'category-removing': u'Robot: Tar bort från %(oldcat)s',
	},
	'szl': {
		'category-adding': u'Bot dodowo: [[Kategoria:%(newcat)s]]',
	},
	# Author: Joseph
	'tr': {
		'category-was-moved': u'Robot: Kategori şuraya taşındı [[:Category:%(newcat)s|%(title)s]]',
		'category-changing': u'Robot: %(oldcat)s değiştiriliyor',
		'category-listifying': u'Bot: Şuradan itibaren listeleniyor %(fromcat)s (%(num)d girdi)',
	},
	# Author: Тест
	'uk': {
		'category-was-moved': u'Робот: категорію перейменовано на [[:Категорія:%(newcat)s|%(title)s]]',
		'category-also-in': u'(також у %(alsocat)s)',
		'category-changing': u'Робот: зміна %(oldcat)s',
		'category-was-disbanded': u'Робот: категорія розформована',
		'category-listifying': u'Робот: складання списку %(fromcat)s з (%(num)d записів)',
		'category-replacing': u'Робот: заміна категорії %(oldcat)s на %(newcat)s',
		'category-adding': u'Робот: додавання [[Категорія:%(newcat)s]]',
		'category-removing': u'Робот: видалення з %(oldcat)s',
	},
	# Author: Minh Nguyen
	'vi': {
		'category-was-moved': u'Rôbốt: Di chuyển thể loại qua [[:Thể loại:%(newcat)s|%(title)s]]',
		'category-also-in': u'(cũng trong %(alsocat)s)',
		'category-changing': u'Rôbốt: Thay đổi %(oldcat)s',
		'category-was-disbanded': u'Rôbốt: Thể loại bị giải tán',
		'category-listifying': u'Rôbốt: Danh sách hóa từ %(fromcat)s (%(num)d trang)',
		'category-replacing': u'Rôbốt: Thay thể loại %(oldcat)s bằng %(newcat)s',
		'category-adding': u'Rôbốt: Thêm [[Thể loại:%(newcat)s]]',
		'category-removing': u'Rôbốt: Dời khỏi %(oldcat)s',
	},
	'vo': {
		'category-adding': u'Bot: läükon: [[Klad:%(newcat)s]]',
	},
	'zh': {
		'category-was-moved': u'機器人:移動目錄至 [[:Category:%(newcat)s|%(title)s]]',
		'category-also-in': u'(也在 %(alsocat)s)',
		'category-changing': u'機器人:變更目錄 [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-was-disbanded': u'機器人:本目錄已解散',
		'category-listifying': u'機器人: 從%(fromcat)提取列表(%(num)d個項目)',
		'category-replacing': u'機器人:變更目錄 [[%(oldcat)s]]→[[%(newcat)s]]',
		'category-adding': u'機器人:新增目錄 [[Category:%(newcat)s]]',
		'category-removing': u'機器人:移除目錄 [[%(oldcat)s]]',
	},
	# Author: Hydra
	'zh-hans': {
		'category-was-moved': u'机器人： 类别移动到 [[:Category:%(newcat)s|%(title)]]',
	},
}