# -*- coding: utf-8 -*-
msg = {
	'ar': {
		'delete-from-category': u'روبوت - حذف كل الصفحات من التصنيف %(page)s',
		'delete-from-file': u'بوت: حذف قائمة من الملفات.',
		'delete-images': u'روبوت -حذف كل الصور في الصفحة %(page)s',
		'delete-linked-pages': u'روبوت - حذف كل الصفحات الموصولة من %(page)s',
		'delete-referring-pages': u'روبوت - حذف كل الصفحات الراجعة من %(page)s',
	},
	'cs': {
		'delete-from-category': u'Robot smazal obsah kategorie %(page)s',
		'delete-from-file': u'Robot smazal podle seznamu',
		'delete-images': u'Robot smazal všechny obrázky z %(page)s',
		'delete-linked-pages': u'Robot smazal vše odkazované z %(page)s',
		'delete-referring-pages': u'Robot smazal vše odkazující na %(page)s',
	},
	'de': {
		'delete-from-category': u'Bot: Lösche alle Seiten in Kategorie %(page)s',
		'delete-linked-pages': u'Bot: Lösche alle in %(page)s verlinkte Seiten',
		'delete-referring-pages': u'Bot: Lösche alle auf %(page)s linkenden Seiten',
	},
	'en': {
		'delete-from-category': u'Robot: Deleting all pages from category %(page)s',
		'delete-from-file': u'Robot: Deleting a list of files.',
		'delete-images': u'Robot: Deleting all images on page %(page)s',
		'delete-linked-pages': u'Robot: Deleting all pages linked from %(page)s',
		'delete-referring-pages': u'Robot: Deleting all pages referring from %(page)s',
	},
	'fa': {
		'delete-from-category': u'ربات:حذف تمام صفحه‌های رده %(page)s',
		'delete-from-file': u'ربات:حذف فهرستی از صفحه‌ها',
		'delete-images': u'ربات: حذف تمام تصویرهای به کار رفته در صفحه %(page)s',
		'delete-linked-pages': u'ربات: حذف تمام صفحه‌هایی که در %(page)s پیوند شده‌اند',
		'delete-referring-pages': u'ربات:حذف تمام صفحه‌هایی که به %(page)s پیوند داده‌اند',
	},
	'fr': {
		'delete-from-category': u'Bot: Supprime toutes pages de la catégorie %(page)s',
		'delete-from-file': u'Robot: Suppression d’une liste de fichiers.',
		'delete-images': u'Robot : Supprime tous les fichiers sur la page %(page)s',
		'delete-linked-pages': u'Robot : Supprime toutes les pages liées depuis %(page)s',
		'delete-referring-pages': u'Robot : Supprime toutes les pages référant à %(page)s',
	},
	'he': {
		'delete-from-category': u'בוט: מוחק את כל הדפים מהקטגוריה %(page)s.',
		'delete-from-file': u'בוט: מוחק רשימת דפים מתוך קובץ.',
		'delete-images': u'בוט: מוחק את כל התמונות בדף %(page)s.',
		'delete-linked-pages': u'בוט: מוחק את כל הדפים המקושרים מהדף %(page)s.',
		'delete-referring-pages': u'בוט: מוחק את כל הדפים המקשרים לדף %(page)s.',
	},
	'lt': {
		'delete-from-category': u'robotas: Trinami visi puslapiai iš kategorijos %(page)s',
		'delete-linked-pages': u'robotas: Trinami visi puslapiai į kuriuos yra nuoroda iš %(page)s',
		'delete-referring-pages': u'robotas: Trinami visi puslapiai rodantys į %(page)s',
	},
	# Author: Siebrand
	'nl': {
		'delete-from-category': u'Robot: alle pagina\'s uit categorie %(page)s worden verwijderd',
		'delete-from-file': u'Robot: lijst met pagina\'s wordt verwijderd.',
		'delete-images': u'Robot: alle media op pagina %(page)s worden verwijderd',
		'delete-linked-pages': u'Robot: alle pagina\'s waar de pagina %(page)s naar verwijst worden verwijderd',
		'delete-referring-pages': u'Robot: alle pagina\'s die naar de pagina %(page)s verwijzen worden verwijderd',
	},
	'pl': {
		'delete-from-category': u'Robot usuwa wszystkie artykuły z kategorii %(page)s',
		'delete-from-file': u'Robot usuwa pliki z listy.',
		'delete-images': u'Robot usuwa wszystkie obrazy w artykule %(page)s',
		'delete-linked-pages': u'Robot usuwa wszystkie artykuły zlinkowane z %(page)s',
		'delete-referring-pages': u'Robot usuwa wszystkie artykuły odnoszące się do %(page)s',
	},
	'pt': {
		'delete-from-category': u'Bot: Apagando todas as páginas da categoria %(page)s',
		'delete-from-file': u'Bot: Apagando um lista de arquivos.',
		'delete-images': u'Bot: Apagando todas as imagens da página %(page)s',
		'delete-linked-pages': u'Bot: Apagando todas as páginas ligadas a %(page)s',
		'delete-referring-pages': u'Bot: Apagando todas as páginas afluentes a %(page)s',
	},
	'ru': {
		'delete-from-category': u'Бот: Удаление всех страниц из категории %(page)s',
		'delete-from-file': u'Бот: Удаление списка файлов.',
		'delete-images': u'Бот: Удаление всех изображений на странице %(page)s',
		'delete-linked-pages': u'Бот: Удаление всех страниц связанных с %(page)s',
		'delete-referring-pages': u'Бот: Удаление всех страниц, относящихся к %(page)s',
	},
	'sv': {
		'delete-from-category': u'Bot: Tar bort alla sidor i kategori %(page)s',
		'delete-from-file': u'Bot: Tar bort fillista.',
		'delete-images': u'Bot: Tar bort alla bilder på sida %(page)s',
		'delete-linked-pages': u'Bot: Tar bort alla sidor länkade från %(page)s',
	},
	'uk': {
		'delete-from-category': u'Бот: Видалення усіх сторінок з категорії %(page)s',
		'delete-from-file': u'Бот: Видалення списку файлів.',
		'delete-images': u'Бот: Видалення усіх зображень із сторінки %(page)s',
		'delete-linked-pages': u'Бот: Видалення усіх сторінок, пов\'язаних із %(page)s',
		'delete-referring-pages': u'Бот: Видалення усіх сторінок, що відносяться до %(page)s',
	},
}