# -*- coding: utf-8 -*-
msg = {
        'ar': {
                'delete-from-category': u'روبوت - حذف كل الصفحات من التصنيف %s',
                'delete-from-file': u'بوت: حذف قائمة من الملفات.',
                'delete-images': u'روبوت -حذف كل الصور في الصفحة %s',
                'delete-linked-pages': u'روبوت - حذف كل الصفحات الموصولة من %s',
                'delete-referring-pages': u'روبوت - حذف كل الصفحات الراجعة من %s',
        },
        'cs': {
                'delete-from-category': u'Robot smazal obsah kategorie %s',
                'delete-from-file': u'Robot smazal podle seznamu',
                'delete-images': u'Robot smazal všechny obrázky z %s',
                'delete-linked-pages': u'Robot smazal vše odkazované z %s',
                'delete-referring-pages': u'Robot smazal vše odkazující na %s',
        },
        'de': {
                'delete-from-category': u'Bot: Lösche alle Seiten in Kategorie %s',
                'delete-linked-pages': u'Bot: Lösche alle in %s verlinkte Seiten',
                'delete-referring-pages': u'Bot: Lösche alle auf %s linkenden Seiten',
        },
        'en': {
                'delete-from-category': u'Bot: Deleting all pages from category %s',
                'delete-from-file': u'Bot: Deleting a list of files.',
                'delete-images': u'Bot: Deleting all images on page %s',
                'delete-linked-pages': u'Bot: Deleting all pages linked from %s',
                'delete-referring-pages': u'Bot: Deleting all pages referring from %s',
        },
        'fa': {
                'delete-from-category': u'ربات:حذف تمام صفحه‌های رده %s',
                'delete-from-file': u'ربات:حذف فهرستی از صفحه‌ها',
                'delete-images': u'ربات: حذف تمام تصویرهای به کار رفته در صفحه %s',
                'delete-linked-pages': u'ربات: حذف تمام صفحه‌هایی که در %s پیوند شده‌اند',
                'delete-referring-pages': u'ربات:حذف تمام صفحه‌هایی که به %s پیوند داده‌اند',
        },
        'fr': {
                'delete-from-category': u'Bot: Supprime toutes pages de la catégorie %s',
                'delete-from-file': u'Robot: Suppression d’une liste de fichiers.',
                'delete-images': u'Robot : Supprime tous les fichiers sur la page %s',
                'delete-linked-pages': u'Robot : Supprime toutes les pages liées depuis %s',
                'delete-referring-pages': u'Robot : Supprime toutes les pages référant à %s',
        },
        'he': {
                'delete-from-category': u'בוט: מוחק את כל הדפים מהקטגוריה %s.',
                'delete-from-file': u'בוט: מוחק רשימת דפים מתוך קובץ.',
                'delete-images': u'בוט: מוחק את כל התמונות בדף %s.',
                'delete-linked-pages': u'בוט: מוחק את כל הדפים המקושרים מהדף %s.',
                'delete-referring-pages': u'בוט: מוחק את כל הדפים המקשרים לדף %s.',
        },
        'lt': {
                'delete-from-category': u'robotas: Trinami visi puslapiai iš kategorijos %s',
                'delete-linked-pages': u'robotas: Trinami visi puslapiai į kuriuos yra nuoroda iš %s',
                'delete-referring-pages': u'robotas: Trinami visi puslapiai rodantys į %s',
        },
        'nl': {
                'delete-from-category': u'Bot: verwijdert alle pagina\'s uit categorie %s',
                'delete-from-file': u'Bot: verwijdert een lijst met pagina\'s.',
                'delete-images': u'Bot: verwijdert alle media op pagina %s',
                'delete-linked-pages': u'Bot: verwijdert alle pagina\'s met een verwijzing naar %s',
                'delete-referring-pages': u'Bot: verwijdert alle pagina\'s met referentie van %s',
        },
        'pl': {
                'delete-from-category': u'Robot usuwa wszystkie artykuły z kategorii %s',
                'delete-from-file': u'Robot usuwa pliki z listy.',
                'delete-images': u'Robot usuwa wszystkie obrazy w artykule %s',
                'delete-linked-pages': u'Robot usuwa wszystkie artykuły zlinkowane z %s',
                'delete-referring-pages': u'Robot usuwa wszystkie artykuły odnoszące się do %s',
        },
        'pt': {
                'delete-from-category': u'Bot: Apagando todas as páginas da categoria %s',
                'delete-from-file': u'Bot: Apagando um lista de arquivos.',
                'delete-images': u'Bot: Apagando todas as imagens da página %s',
                'delete-linked-pages': u'Bot: Apagando todas as páginas ligadas a %s',
                'delete-referring-pages': u'Bot: Apagando todas as páginas afluentes a %s',
        },
        'ru': {
                'delete-from-category': u'Бот: Удаление всех страниц из категории %s',
                'delete-from-file': u'Бот: Удаление списка файлов.',
                'delete-images': u'Бот: Удаление всех изображений на странице %s',
                'delete-linked-pages': u'Бот: Удаление всех страниц связанных с %s',
                'delete-referring-pages': u'Бот: Удаление всех страниц, относящихся к %s',
        },
        'sv': {
                'delete-from-category': u'Bot: Tar bort alla sidor i kategori %s',
                'delete-from-file': u'Bot: Tar bort fillista.',
                'delete-images': u'Bot: Tar bort alla bilder på sida %s',
                'delete-linked-pages': u'Bot: Tar bort alla sidor länkade från %s',
        },
        'uk': {
                'delete-from-category': u'Бот: Видалення усіх сторінок з категорії %s',
                'delete-from-file': u'Бот: Видалення списку файлів.',
                'delete-images': u'Бот: Видалення усіх зображень із сторінки %s',
                'delete-linked-pages': u'Бот: Видалення усіх сторінок, пов\'язаних із %s',
                'delete-referring-pages': u'Бот: Видалення усіх сторінок, що відносяться до %s',
        },
}
