# -*- coding: utf-8 -*-
msg = {
	'en': {
		'reflinks-autogen': u'autogenerated',
		'reflinks-msg': u'Bot: Converting bare references, using ref names to avoid duplicates, see [[%(manual)s|FAQ]]',
		'reflinks-comment': u'Bot generated title',
	},
	# Author: Shirayuki
	'qqq': {
		'reflinks-autogen': u'A short identifier for autogenerated reference titles',
		'reflinks-comment': u'A hint what the bot adds between <code><nowiki><!-- --></nowiki></code> when converts bare references.\n\nPreceded by the title, so this message means "title which is generated by bot".',
		'reflinks-msg': u'Edit summary when the bot places a title for a bare html link inside references\n* %(manual)s - a interlanguage link to the bot\'s localized manual, usually [[mw:Manual:Pywikibot/refLinks]]',
	},
	'ar': {
		'reflinks-autogen': u'مولد تلقائيا',
		'reflinks-comment': u'عنوان مولد بالبوت',
	},
	# Author: Xuacu
	'ast': {
		'reflinks-autogen': u'xeneráu automáticamente',
		'reflinks-comment': u'Títulu xeneráu por un bot',
		'reflinks-msg': u'Bot: Convertiendo referencies pures, usando los nomes de ref pa evitar duplicaos, vea [[%(manual)s|FAQ]]',
	},
	# Author: Fohanno
	'br': {
		'reflinks-autogen': u'emc\'hanet',
		'reflinks-comment': u'Titl savet gant ur robot',
	},
	# Author: Alvaro Vidal-Abarca
	'ca': {
		'reflinks-autogen': u'autogenerats',
		'reflinks-comment': u'Títol generat per bot',
		'reflinks-msg': u'Bot: convertint referències nues, usant noms de referències per evitar duplicats, vegeu [[%(manual)s|FAQ]]',
	},
	# Author: Chmee2
	# Author: Matěj Grabovský
	'cs': {
		'reflinks-autogen': u'vytvořeno automaticky',
		'reflinks-comment': u'Název vygenerovaný botem',
		'reflinks-msg': u'Robot převedl holé odkazy a pojmenoval reference pro eliminaci duplicit, viz [[%(manual)s|manuál]]',
	},
	'da': {
		'reflinks-autogen': u'autogeneret',
		'reflinks-comment': u'Bot genereret titel',
		'reflinks-msg': u'Bot: Tilføjer beskrivelse til eksterne links, se [[%(manual)s|FAQ]]',
	},
	# Author: Metalhead64
	'de': {
		'reflinks-autogen': u'automatisch erzeugt',
		'reflinks-comment': u'Automatisch generierter Titel',
		'reflinks-msg': u'Bot: Korrektes Referenzformat (siehe [[%(manual)s]])',
	},
	# Author: Marmase
	'diq': {
		'reflinks-autogen': u'otomatik vıraziya',
		'reflinks-comment': u'Boti sername vıraşt',
		'reflinks-msg': u'Boto  referansane çerğbiyayışane mıracat kerdışan name keno , bıvin [[%(manual)s|FAQ]]',
	},
	# Author: Geraki
	'el': {
		'reflinks-autogen': u'δημιουργήθηκε αυτόματα',
		'reflinks-comment': u'Τίτλος που δημιουργήθηκε από bot',
		'reflinks-msg': u'Bot: Μετατροπή απλών αναφορών, χρησιμοποιώντας ονόματα ref για να αποφευχθούν διπλότυπες, δείτε το [[%(manual)s|FAQ]]',
	},
	# Author: Fitoschido
	'es': {
		'reflinks-autogen': u'generado automáticamente',
		'reflinks-comment': u'Título generado por un bot',
		'reflinks-msg': u'Formateando las referencias que no tuvieran títulos (FAQ : [[%(manual)s]])',
	},
	# Author: Reza1615
	'fa': {
		'reflinks-autogen': u'تولید خودکار',
		'reflinks-comment': u'عنوان تصحیح شده توسط ربات',
		'reflinks-msg': u'ربات:تصحیح پيوند به بيرون يا عنوان پيوند. [[%(manual)s|اطلاعات بیشتر]]',
	},
	# Author: Silvonen
	'fi': {
		'reflinks-autogen': u'automaattisesti tuotettu',
		'reflinks-comment': u'Botin tuottama otsikko',
	},
	# Author: Gomoko
	'fr': {
		'reflinks-autogen': u'auto-généré',
		'reflinks-comment': u'Titre généré automatiquement',
		'reflinks-msg': u'Bot: Correction des refs. mal formatées, suppression doublons en utilisant des références nommées (cf. [[%(manual)s|explications]])',
	},
	# Author: Murma174
	'frr': {
		'reflinks-autogen': u'automaatisk maaget',
		'reflinks-comment': u'Automaatisk maaget tiitel',
		'reflinks-msg': u'Bot: Referensen konwertiaret an iandüüdag maaget, luke uk [[%(manual)s|diar]]',
	},
	# Author: Toliño
	'gl': {
		'reflinks-autogen': u'xerado automaticamente',
		'reflinks-comment': u'Título xerado por un bot',
		'reflinks-msg': u'Bot: Melloro as referencias sen formato, poño nomes ás referencias para evitar duplicados ([[%(manual)s|preguntas frecuentes]])',
	},
	'he': {
		'reflinks-msg': u'בוט:מלביש קישורים חיצוניים. (FAQ : [[%(manual)s]])',
	},
	'hu': {
		'reflinks-comment': u'Robot generálta cím',
		'reflinks-msg': u'Robot: Forráshivatkozások kibővítése a hivatkozott oldal címével',
	},
	# Author: M hamlet
	'hy': {
		'reflinks-autogen': u'ավտոմատ գեներացված',
	},
	# Author: McDutchie
	'ia': {
		'reflinks-autogen': u'generate automaticamente',
		'reflinks-comment': u'Titulo generate per robot',
		'reflinks-msg': u'Robot: Corrige referentias sin formato, attribuente nomines pro evitar duplicatos; vide le [[%(manual)s|FAQ]]',
	},
	'it': {
		'reflinks-autogen': u'autogenerato',
		'reflinks-comment': u'Titolo generato automaticamente',
		'reflinks-msg': u'Bot: Sistemo note con collegamenti esterni senza titolo ([[%(manual)s|documentazione]])',
	},
	# Author: Shirayuki
	'ja': {
		'reflinks-autogen': u'自動生成',
		'reflinks-comment': u'ボットが生成したタイトル',
	},
	# Author: 아라
	'ko': {
		'reflinks-autogen': u'자동 생성됨',
		'reflinks-comment': u'봇이 따온 제목',
		'reflinks-msg': u'봇: url만 있는 주석을 보강, (영문)[[%(manual)s]] 참조',
	},
	# Author: Purodha
	'ksh': {
		'reflinks-autogen': u'automattesch aanjelaat',
		'reflinks-comment': u'Dä Tettel es vun Bot faßjelaat un ußjedaach.',
		'reflinks-msg': u'Bot: Verweise krijje Nahme, öm kein dubelte ze krejje. Loor noh de [[%(manual)s|öff jschtallte Froore un dänne ier Antwoote]].',
	},
	# Author: Robby
	'lb': {
		'reflinks-autogen': u'automatesch generéiert',
		'reflinks-comment': u'Automatesch generéierten Titel',
		'reflinks-msg': u'Bot: Verbesserung vun de Referenzen, et ginn Nimm vu Referenze benotzt fir Doublonen ze verhënneren, kuckt d\'[[%(manual)s|FAQen]]',
	},
	# Author: Bjankuloski06
	'mk': {
		'reflinks-autogen': u'автосоздадено',
		'reflinks-comment': u'Насловот е ставен од бот',
		'reflinks-msg': u'Бот: Исправка на наводите користејќи именувани наводи за да се избегнат дупликати, погл. [[%(manual)s|ЧПП]]',
	},
	# Author: Praveenp
	'ml': {
		'reflinks-autogen': u'സ്വയം നിർമ്മിച്ചത്',
		'reflinks-comment': u'ബോട്ട് നിർമ്മിച്ച തലക്കെട്ട്',
	},
	# Author: Anakmalaysia
	'ms': {
		'reflinks-autogen': u'hasilan automatik',
		'reflinks-comment': u'Tajuk hasilan bot',
		'reflinks-msg': u'Bot: Menukarkan rujukan kosong, menggunakan nama ref untuk mengelakkan duplikasi, rujuk [[%(manual)s|FAQ]]',
	},
	# Author: सरोज कुमार ढकाल
	'ne': {
		'reflinks-autogen': u'autogenerated',
		'reflinks-comment': u'बोटले सिर्जना गरेको शिर्षक',
		'reflinks-msg': u'बोट: खुला रिफरेन्सहरू हटाउँदै , दोहोरिन नदिन रेफ नाम दिँदै, कृपया [[%(manual)s|FAQ]]मा हेर्नुहोला',
	},
	# Author: Siebrand
	'nl': {
		'reflinks-autogen': u'automatisch aangemaakt',
		'reflinks-comment': u'Door robot aangemaakte titel',
		'reflinks-msg': u'Robot: converteren van referenties om duplicate te voorkomen, zie [[%(manual)s|FAQ]]',
	},
	# Author: Cocu
	'no': {
		'reflinks-autogen': u'autogenerert',
		'reflinks-comment': u'Botgenerert tittel',
		'reflinks-msg': u'Bot: Konverterer nakne referanser ved å bruke referansenavn for å unngå duplikater, se [[%(manual)s|OSS]]',
	},
	# Author: Rzuwig
	'pl': {
		'reflinks-autogen': u'wygenerowany automatycznie',
		'reflinks-comment': u'Tytuł wygenerowany przez bota',
		'reflinks-msg': u'Bot: Dodanie tytułów do linków w przypisach (patrz [[%(manual)s|FAQ]])',
	},
	# Author: Giro720
	'pt': {
		'reflinks-autogen': u'gerado automaticamente',
		'reflinks-comment': u'Título gerado pelo bot',
		'reflinks-msg': u'Bot: a converter referências vazias, usando nomes de referências para evitar duplicidade, veja [[%(manual)s|FAQ]]',
	},
	# Author: Prilopes
	# Author: TheGabrielZaum
	'pt-br': {
		'reflinks-autogen': u'gerado automaticamente',
		'reflinks-comment': u'Título gerado pelo Bot',
		'reflinks-msg': u'Bot: convertendo referências vazias, usando nomes de referências para evitar duplicidade, veja [[%(manual)s|FAQ]]',
	},
	# Author: Minisarm
	'ro': {
		'reflinks-autogen': u'autogenerat',
		'reflinks-comment': u'Titlu generat de robot',
	},
	# Author: Okras
	'ru': {
		'reflinks-autogen': u'сгенерировано автоматически',
		'reflinks-comment': u'Заголовок добавлен ботом',
		'reflinks-msg': u'бот: добавление заголовков в сноски; исправление двойных сносок, см. [[%(manual)s|ЧаВо]]',
	},
	# Author: Tobulos1
	# Author: WikiPhoenix
	'sv': {
		'reflinks-autogen': u'automatiskt genererade',
		'reflinks-comment': u'Botgenererad titel',
	},
	# Author: Andriykopanytsia
	'uk': {
		'reflinks-autogen': u'автоматично згенероване',
		'reflinks-comment': u'Заголовок доданий ботом',
		'reflinks-msg': u'Бот: перетворення чистих посилань за допомогою назв для уникнення дублікатів, див. [[%(manual)s|ЧаП]]',
	},
	# Author: Minh Nguyen
	'vi': {
		'reflinks-autogen': u'tạo tự động',
		'reflinks-comment': u'Tên do bot tạo tự động',
		'reflinks-msg': u'Bot: Chuyển đổi các tham chiếu thuần dùng tên ref để tránh tham chiếu thừa; xem [[%(manual)s|câu hỏi thường gặp]]',
	},
	# Author: Yfdyh000
	'zh': {
		'reflinks-autogen': u'自动生成',
		'reflinks-comment': u'机器人生成的标题',
		'reflinks-msg': u'机器人：转换光秃引用，使用ref名称避免重复，见[[%(manual)s|常见问题]]',
	},
	# Author: Justincheng12345
	'zh-hant': {
		'reflinks-autogen': u'自動生成',
		'reflinks-comment': u'由機械人創建標題',
		'reflinks-msg': u'機械人轉換純引用至使用ref-names以避免重覆，見[[%(manual)s|常見問題]]',
	},
};
