# -*- coding: utf-8 -*-
msg = {
	'en': {
		'reflinks-autogen': u'autogenerated',
		'reflinks-msg': u'Bot: Converting bare references, using ref names to avoid duplicates, see [[%(manual)s|FAQ]]',
		'reflinks-comment': u'Bot generated title',
	},
	'qqq': {
		'reflinks-autogen': u'A short identifier for autogenerated reference titles',
		'reflinks-msg': u'Edit summary when the bot places a title for a bare html link inside references\n* %(manual)s - a interlanguage link to the bot\'s localized manual, usually [[mw:Manual:Pywikibot/refLinks]]',
		'reflinks-comment': u'A hint what the bot adds between <code><nowiki><!-- --></nowiki></code> when converts bare references',
	},
	'ar': {
		'reflinks-autogen': u'مولد تلقائيا',
		'reflinks-comment': u'عنوان مولد بالبوت',
	},
	'da': {
		'reflinks-autogen': u'autogeneret',
		'reflinks-msg': u'Bot: Tilføjer beskrivelse til eksterne links, se [[%(manual)s|FAQ]]',
		'reflinks-comment': u'Bot genereret titel',
	},
	'de': {
		'reflinks-msg': u'Bot: Korrektes Referenzformat (siehe [[%(manual)s]])',
		'reflinks-comment': u'Automatisch generierter Titel',
	},
	'es': {
		'reflinks-msg': u'Formateando las referencias que no tuvieran títulos (FAQ : [[%(manual)s]])',
		'reflinks-comment': u'Título generado por un bot',
	},
	'fa': {
		'reflinks-msg': u'ربات:تصحیح پيوند به بيرون يا عنوان پيوند. [[%(manual)s|اطلاعات بیشتر]]',
		'reflinks-comment': u'عنوان تصحیح شده توسط ربات',
	},
	'fr': {
		'reflinks-msg': u'Bot: Correction des refs. mal formatées, suppression doublons en utilisant des références nommées (cf. [[%(manual)s|explications]])',
		'reflinks-comment': u'Titre généré automatiquement',
	},
	'he': {
		'reflinks-msg': u'בוט:מלביש קישורים חיצוניים. (FAQ : [[%(manual)s]])',
	},
	'hu': {
		'reflinks-msg': u'Robot: Forráshivatkozások kibővítése a hivatkozott oldal címével',
		'reflinks-comment': u'Robot generálta cím',
	},
	'it': {
		'reflinks-autogen': u'autogenerato',
		'reflinks-msg': u'Bot: Sistemo note con collegamenti esterni senza titolo ([[%(manual)s|documentazione]])',
		'reflinks-comment': u'Titolo generato automaticamente',
	},
	'ko': {
		'reflinks-msg': u'봇: url만 있는 주석을 보강, (영문)[[%(manual)s]] 참조',
		'reflinks-comment': u'봇이 따온 제목',
	},
	'pl': {
		'reflinks-msg': u'autonazwa',
		'reflinks-msg': u'Bot: Dodanie tytułów do linków w przypisach (patrz [[%(manual)s|FAQ]])',
		'reflinks-comment': u'Tytuł wygenerowany przez bota',
	},
	'ru': {
		'reflinks-msg': u'Робот: добавление заголовков в сноски; исправление двойных сносок',
		'reflinks-comment': u'Заголовок добавлен ботом',
	},
};
