# -*- coding: utf-8 -*-
msg = {
    'ar': {'replace-replacing': u'%(description)s روبوت : استبدال تلقائي للنص',
    },
    'ca': {'replace-replacing': u'Robot: Reemplaçament automàtic de text %(description)s',
    },
    'cs': {'replace-replacing': u'Robot automaticky nahradil text: %(description)s',
    },
    'de': {'replace-replacing': u'Bot: Automatisierte Textersetzung %(description)s',
    },
    'el': {'replace-replacing': u'Ρομπότ: Αυτόματη αντικατάσταση κειμένου %(description)s',
    },
    'en': {'replace-replacing': u'Bot: Automated text replacement %(description)s',
    },
    'es': {'replace-replacing': u'Robot: Reemplazo automático de texto %(description)s',
    },
    'fa': {'replace-replacing': u'ربات: تغییر خودکار متن %(description)s',
    },
    'fi': {'replace-replacing': u'Botti korvasi automaattisesti tekstin %(description)s',
    },
    'fr': {'replace-replacing': u'Robot : Remplacement de texte automatisé %(description)s',
    },
    'frr': {'replace-replacing': u'Bot: Automatisiaret ütjwakselt tekst %(description)s',
    },
    'he': {'replace-replacing': u'בוט: החלפת טקסט אוטומטית %(description)s',
    },
    'hu': {'replace-replacing': u'Robot: Automatikus szövegcsere %(description)s',
    },
    'ia': {'replace-replacing': u'Robot: Reimplaciamento automatic de texto %(description)s',
    },
    'id': {'replace-replacing': u'Bot: Penggantian teks otomatis %(description)s',
    },
    'is': {'replace-replacing': u'Vélmenni: breyti texta %(description)s',
    },
    'it': {'replace-replacing': u'Bot: Sostituzione automatica %(description)s',
    },
    'ja': {'replace-replacing': u'ロボットによる: 文字置き換え %(description)s',
    },
    'ka': {'replace-replacing': u'რობოტი: ტექსტის ავტომატური შეცვლა %(description)s',
    },
    'kk': {'replace-replacing': u'Бот: Мәтінді өздікті алмастырды: %(description)s',
    },
    'ksh': {'replace-replacing': u'Bot: hät outomatesch Täx jetuusch: %(description)s',
    },
    'lt': {'replace-replacing': u'robotas: Automatinis teksto keitimas %(description)s',
    },
    'nds': {'replace-replacing': u'Bot: Text automaatsch utwesselt: %(description)s',
    },
    'nds-nl': {'replace-replacing': u'Bot: autematisch tekse vervungen %(description)s',
    },
    'nl': {'replace-replacing': u'Bot: automatisch tekst vervangen %(description)s',
    },
    'nn': {'replace-replacing': u'robot: automatisk teksterstatning: %(description)s',
    },
    'no': {'replace-replacing': u'robot: automatisk teksterstatning: %(description)s',
    },
    'pl': {'replace-replacing': u'Robot automatycznie zamienia tekst %(description)s',
    },
    'pt': {'replace-replacing': u'Bot: Mudança automática %(description)s',
    },
    'ru': {'replace-replacing': u'Робот: Автоматизированная замена текста %(description)s',
    },
    'sr': {'replace-replacing': u'Бот: Аутоматска замена текста %(description)s',
    },
    'sv': {'replace-replacing': u'Bot: Automatisk textersättning: %(description)s',
    },
    'uk': {'replace-replacing': u'Бот: Автоматизована заміна тексту: %(description)s',
    },
    'zh': {'replace-replacing': u'機器人:執行文字代換作業 %(description)s',
    },
}
