# -*- coding: utf-8 -*-
msg = {
	# Author: Naudefj
	'af': {
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Kennisgewing',
	},
	# Author: Meno25
	'ar': {
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'رسالة روبوت',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'روبوت',
	},
	# Author: DrTrigon
	# Author: Xuacu
	'ast': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'trocando etiqueta(es) %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Alderique camudáu',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Alderique zarráu',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MENSAXE DE ROBOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nuevu alderique',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notificación',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s cabera edición] (%(page_size)s bytes) fecha por %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s tolos alderiques acabaron (vixilancia detenida) - cabera edición fecha por %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nResume xeneráu dende y en: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(nun s\'alcontró dengún editor humanu)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - cabera edición fecha por [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Mensaxe d\'avisu de robot: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Amestáu resume d\'alderique: %(num)i entraes',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Amestáu resume d\'alderique con llimpieza: %(num)i entraes',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Anováu resume d\'alderique: %(num)i entraes en %(page)s',
	},
	# Author: Cekli829
	# Author: Vago
	'az': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Müzakirə səhifəsi dəyişildi',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Müzakirə bağlandı',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'ROBOT MESAJI',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Yeni müzakirə',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Bildiriş',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
	},
	# Author: EugeneZelenko
	# Author: Jim-by
	# Author: DrTrigon
	# Author: Renessaince
	'be-x-old': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'замена %(tags)s цэтлікаў',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Абмеркаваньне зьмененае',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Абмеркаваньне закрытае',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'ПАВЕДАМЛЕНЬНЕ РОБАТА',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Новае абмеркаваньне',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Абвяшчэньне',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s — [%(history_link)s апошняе рэдагаваньне] (%(page_size)s байт(ы/аў)) %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s усе абмеркаваньні скончаныя (сачэньне спыненае) — апошняе рэдагаваньне %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nСтворанае апісаньне з і на: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(няма рэдагаваньняў зробленых чалавекам)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> — апошняе рэдагаваньне [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Папярэджаньне робата: %(page)s «\'\'%(warning)s\'\'»',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Дададзенае кароткае апісаньне абмеркаваньня: %(num)i запіс(ы/аў)',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Дададзенае апісаньне абмеркаваньня з папраўкамі: %(num)i запіс(ы/аў)',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'робат',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Абноўленае апісаньне абмеркаваньня: %(num)i запіс(ы/аў) у %(page)s',
	},
	# Author: DCLXVI
	'bg': {
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'робот',
	},
	# Author: Fulup
	# Author: Y-M D
	# Author: DrTrigon
	'br': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'Oc\'h erlec\'hiañ an tikedennoù %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Kaozeadenn kemmet',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Serr eo ar gaoz',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'KEMENNADENN ROBOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Kaozeadenn nevez',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Kemennadenn',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s kemm diwezhañ] (%(page_size)s okted) gant %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s kloz eo an holl gaozeadennoù (paouezet da evezhiañ) - kemmet da ziwezhañ gant %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nBomm diverrañ ganet adalek ha da : %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(n\'eus bet kavet aozer denel ebet)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - kemm diwezhañ gant [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Kemenn diwall a-berzh ar robot : %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Bomm diverrañ ar gaoz ouzhpennet : %(num)i moned',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Bomm diverrañ ar gaoz ouzhpennet gant un taol naetaat : %(num)i moned',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Hizivaet bomm diverrañ ar gaoz : %(num)i moned e %(page)s',
	},
	# Author: Edinwiki
	'bs': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'zamjena %(tags)s oznaka',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Rasprava izmjenjena',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Rasprava zatvorena',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'PORUKA BOTA',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nova rasprava',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Obavještenje',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s zadnja izmjena] (%(page_size)s bajtova) od %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s sve rasprave su završene (nadzor zaustavljen) - zadnja izmjena od %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nSažetak generisan od i na: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(ljudski urednik nije pronađen)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - zadnja izmjena od [[Korisnik:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Upozorenje bota: %(page)s "\'\'%(warning)s\'\'".',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Sažetak rasprave dodan; %(num)i unosa.',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Sažetak rasprave dodan sa čiščenjem: %(num)i unosa.',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Sažetak rasprave ažuriran: %(num)i unosa kod %(page)s.',
	},
	# Author: SMP
	'ca': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discussió alterada',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discussió tancada',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MISSATGE DE ROBOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nova discussió',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notificació',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s; [%(history_link)s darrera modificació] (%(page_size)s octets) per %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s les discussions han acabat (vigilància aturada). Darrera modificació per %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nResum generat des de: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(no s\'ha trobat cap editor humà)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span>; darrera modificació per [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Missatge d\'advertiment de robot: %(page)s «%(warning)s»',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Afegit resum de discussió: %(num)i entrades',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Resum de discussió afegit amb neteja: %(num)i entrades',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Actualitzat resum de discussió:  %(num)i entrades a %(page)s',
	},
	# Author: Asoxor
	'ckb': {
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'پەیامی ڕۆبۆت',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'ڕۆبۆت',
	},
	# Author: Spiffyk
	'cs': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Diskuse změněna',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Diskuse uzavřena',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'ZPRÁVA ROBOTA',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nová diskuse',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Upozornění',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [poslední úprava %(history_link)s] (%(page_size)s bajtů) %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s všechny diskuse skončily (dozor skončil) - naposledy upravil/a %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nShrnutí vygenerováno z a v: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(nebyl nalezen žádný lidský redaktor)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - naposledy upravil/a [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Varování robota: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Přidáno shrnutí diskuse: %(num)i příspěvků',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Přidáno shrnutí diskuse s pročištěním: %(num)i příspěvků',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Upraveno shrnutí diskuse: %(num)i příspěvků na %(page)s stránkách',
	},
	# Author: DrTrigon
	'de': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'substituiere %(tags)s tag(s)',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Diskussion verändert',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Diskussion abgeschlossen',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'BOT MESSAGE',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Neue Diskussion',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Benachrichtigung',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s letzte Bearbeitung] (%(page_size)s Bytes) von %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s alle Diskussionen wurden beendet (Überwachung gestoppt) - letzte Bearbeitung von %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nZusammenfassung erstellt von und um: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(keinen menschlichen Bearbeiter gefunden)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - letzte Bearbeitung von [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Bot Warn-Nachricht: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Diskussions-Zusammenfassung hinzugefügt (%(num)i Einträge)',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Diskussions-Zusammenfassung hinzugefügt und bereinigt (%(num)i Einträge)',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'Bot:',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Diskussions-Zusammenfassung aktualisiert (%(num)i Einträge in %(page)s)',
	},
	# Author: Erdemaslancan
	'diq': {
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Mınaqeşeyo newe',
	},
	# Author: Geraki
	# Author: Glavkos
	# Author: Evropi
	'el': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Η συζήτηση άλλαξε',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Νέα συζήτηση',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Κοινοποίηση',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s τελευταία επεξεργασία] (%(page_size)s bytes) από %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(δεν βρέθηκε ανθρώπινος χρήστης)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - τελευταία επεξεργασία από [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u': * Προειδοποιητικό μήνυμα από ρομπότ: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'ρομπότ',
	},
	# Author: DrTrigon
	'en': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'substituting %(tags)s tag(s)',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discussion changed',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discussion closed',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'ROBOT MESSAGE',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'New Discussion',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notification',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s last edit] (%(page_size)s bytes) by %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s all discussions have finished (surveillance stopped) - last edit by %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nSummary generated from and at: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(no human editor found)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - last edit by [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Robot warning message: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Discussion summary added: %(num)i entries',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Discussion summary added with clean up: %(num)i entries',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Discussion summary updated: %(num)i entries in %(page)s',
	},
	# Author: Vivaelcelta
	# Author: Armando-Martin
	'es': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'sustituyendo las etiqueta(s) %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discusión modificada',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discusión cerrada',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MENSAJE DEL BOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nueva discusión',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notificación',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s última edición] (%(page_size)s bytes) hecha por %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s todas las discusiones han acabado (vigilancia detenida); última edición hecha por %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nResumen generado desde y en: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(no se encontró ningún editor humano)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span>; última edición hecha por [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u': * Mensaje de advertencia del bot: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Añadido el resumen de la discusión: %(num)i entradas',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Añadido el resumen de la discusión con limpieza: %(num)i entradas',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Actualizando el resumen de la discusión: %(num)i entradas en %(page)s',
	},
	# Author: Mjbmr
	# Author: ZxxZxxZ
	# Author: Reza1615
	'fa': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'بحث تغییر کرد',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'بحث بسته شد',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'***پیام ربات***',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'بحث جدید',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'اطلاعیه',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s last edit] (%(page_size)s bytes) by %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nخلاصهٔ ویرایش تولید شد از و در: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'هیچ انسان ویرایشگری یافت نشد.',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - آخرین ویرایش توسط [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u'پیام هشدار ربات : %(page)s «\'\'%(warning)s\'\'»',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'خلاصه بحث‌ها: %(num)i  مطلب',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'ربات',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'به‌روز شده خلاصه بحث‌: %(num)i  مطلب  در %(page)s',
	},
	# Author: Crt
	# Author: Nedergard
	'fi': {
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Uusi keskustelu',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'botti',
	},
	# Author: EileenSanda
	'fo': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Kjakið er broytt',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Kjak er stongt',
	},
	# Author: Gomoko
	# Author: DrTrigon
	# Author: Od1n
	'fr': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'substitution de(s) balise(s) %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discussion modifiée',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discussion fermée',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MESSAGE DU ROBOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nouvelle discussion',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notification',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s : %(page_sections)s - [%(history_link)s dernière modification] (%(page_size)s octets) par %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s : %(page)s toutes les discussions sont terminées (surveillance stoppée) - dernière modification par %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nRésumé généré depuis et à : %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(aucun éditeur humain trouvé)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s : <span class="plainlinks">[%(page_link)s %(page)s]</span> - dernière modification par [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Message d\'avertissement du robot : %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Sommaire de la discussion ajouté : %(num)i entrées',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Sommaire de la discussion ajouté avec nettoyage : %(num)i entrées',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Résumé de la discussion mis à jour : %(num)i entrées dans %(page)s',
	},
	# Author: ChrisPtDe
	# Author: DrTrigon
	'frp': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discussion changiê',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discussion cllôsa',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MÈSSÂJO ROBOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Novèla discussion',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notificacion',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s dèrriér changement] (%(page_size)s octèts) per %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s totes les discussions sont chavonâs (survelyence arrètâ) - dèrriér changement per %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nSomèro fêt dês et a : %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(gins d’èditor humen trovâ)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - dèrriér changement per [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Mèssâjo d’avèrtissement u robot : %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Somèro de la discussion apondu : %(num)i entrâs',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Somèro de la discussion apondu avouéc neteyâjo : %(num)i entrâs',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Somèro de la discussion betâ a jorn : %(num)i entrâs dens %(page)s',
	},
	# Author: DrTrigon
	# Author: Murma174
	'frr': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Diskusjuun feranert',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Diskusjuun ufslööden',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'BOT NOORACHT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nei diskusjuun',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Nooracht',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s leetst feranerang] (%(page_size)s bytes) faan %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s aal jo diskusjuunen san ufslööden (woort ei muar beaachtet) - leetst feranerang faan %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nTuupfaadet faan: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(nään bewerker fünjen)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - leetst feranerang faan [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Bot waarskauet: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Diskusjuun tuupfaadet: %(num)i entries',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Diskusjuun tuupfaadet an apredet: %(num)i entries',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'Bot:',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Diskusjuun tuupfaadet an apredet: %(num)i entries in %(page)s',
	},
	# Author: Toliño
	# Author: DrTrigon
	'gl': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'substituída(s) a(s) etiqueta(s) %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Conversa modificada',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Conversa pechada',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MENSAXE DO BOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nova conversa',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notificación',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s última edición] (%(page_size)s bytes) feita por %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s todas as conversas remataron (vixilancia detida); última edición feita por %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nResumo xerado desde e en: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(non se atopou ningún editor humano)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span>; última edición feita por [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Mensaxe de aviso do bot: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Engadido o resumo da conversa: %(num)i entradas',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Engadido o resumo da conversa con limpeza: %(num)i entradas',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Actualizado o resumo da conversa: %(num)i entradas en %(page)s',
	},
	# Author: Als-Chlämens
	'als': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Diskussion veränderet',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Diskussion abgschlosse',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'BOT MESSAGE',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nöii Diskussion',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Mitteilig',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s letschti Bearbeitig] (%(page_size)s Bytes) vo %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s alli Diskussione sin abgschlosse worde (Überwachig gstoppt) - letschti Bearbeitig vo %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nZämmefassig erstellt vo un um: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(kei mänschliche Benutzer gfunde)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - letschti Bearbeitg vum [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Bötli Warnmäldig: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Diskussions-Zämmefassig dezuegfiegt (%(num)i Yyträg)',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Diskussions-Zämmefassig dezuegfiegt un uffgrüümt (%(num)i Yyträg)',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'Bötli:',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Diskussions-Zämmefassig aktualisiert (%(num)i Yyträg in %(page)s)',
	},
	# Author: Amire80
	# Author: Ofekalef
	'he': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'שיחה שונתה',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'שיחה נסגרה',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'הודעת רובוט',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'דיון חדש',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'הודעה',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nתקציר יוצר מתוך וב־: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(לא נמצא עורך אנושי)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d ב%B %Y',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'רובוט',
	},
	# Author: Dj
	'hu': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Vita módosult',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Téma lezárva',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'BOT ÜZENET',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Új téma',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Értesítés',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s utolsó szerkesztés] (%(page_size)s bájt) szerkesztette: %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s minden téma véget ért (felmérés lezárva) - utolsó szerkesztő: %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nÖsszesítés: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(nem található emberi szerkesztő)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - utoljára [[User:%(user)s]] szerkesztette (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %Y. %B %d.',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':*Bot figyelmeztető üzenet: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Vita összefoglaló hozzáadva: %(num)i hozzászólás',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Vita összefoglaló hozzáadva takarítással: %(num)i hozzászólás',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Vita összefoglaló módosítva: %(num)i hozzászólás a(z) %(page)s oldalon',
	},
	# Author: DrTrigon
	# Author: McDutchie
	'ia': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'substitue le etiquetta(s) %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discussion cambiate',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discussion claudite',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MESSAGE DEL ROBOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nove discussion',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notification',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s ultime modification] (%(page_size)s bytes) per %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s tote le discussiones ha finite (surveliantia terminate) - ultime modification per %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nGeneration del summario: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(nulle redactor human trovate)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - ultime modification per [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; le %d de %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Advertimento del robot: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Summario del discussion addite: %(num)i entratas',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Summario del discussion addite con nettation: %(num)i entratas',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Summario del discussion actualisate: %(num)i entratas in %(page)s',
	},
	# Author: Lam-ang
	'ilo': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Nasukatan ti pagtungtungan',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Narikpan ti pagtungtungan',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MENSAHE TI ROBOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Baro a  pagtungtungan',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Pakaammo',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s naudi a pang-urnos] (%(page_size)s bytes) babaen ti %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s nalpas aminen a pagtungtungan (ti panagsipsiput ket naisardeng) - naudi a panag-urnos babaen ni %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'Ti pakabuklan ket naaramid manipud idiay ken idiay: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(awan ti nabirukan a tao nga agur-urnos)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - naudi a panag-unos babaen ni [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Ballaag a mensahe ti robot: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Nanayonan ti pakabuklan ti tungtungan: %(num)i dagiti naikabil',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Nanayonan ti pakabuklan ti pagtungtungan ti panagdalus: %(num)i dagiti naikabil',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Ti pakabuklan ti pagtungtungan ket napabaro: %(num)i dagiti naikabil idiay %(page)s',
	},
	# Author: Snævar
	'is': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'skipti út %(tags)s tögum',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Umræðu breytt',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Loka umræðu',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'Skilaboð vélmennis',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Ný umræða',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Tilkynning',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: [%(history_link)s síðustu breytingu] (%(page_size)s bæti) undir %(page sections)s eftir %(user)s (%(time)s).',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: Umræðu á %(page)s er lokið. Síðasta breyting var eftir %(user)s (%(time)s).',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nSkilaboð búin til frá: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(enginn mannlegur notandi fannst)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: síðustu breytingu eftir [[User:%(user)s]] (%(time)s) á  <span class="plainlinks">[%(page_link)s %(page)s]</span>',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u';  %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u'Vélmenni: Sendi viðvörunarskilaboðin "\'\'%(warning)s\'\'" á %(page)s',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Yfirliti umræðu bætt við: %(num)i færslur',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Yfirliti umræðu bætt við með fjarlægingu %(num)i færslna',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'vélmenni',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Yfirlit umræðu uppfært: %(num)i færslur á %(page)s',
	},
	# Author: Aushulz
	# Author: Gianfranco
	# Author: Nemo bis
	# Author: Beta16
	'it': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'sostituisco tag(s) %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discussione modificata',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discussione chiusa',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MESSAGGIO DEL ROBOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nuova discussione',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notifica',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s ultima modifica] (%(page_size)s byte) effettuata da %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s - tutte le discussioni sono oramai da considerarsi terminate (monitoraggio arrestato) - ultimo edit effettuato da %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nRiassunto generato da ed a: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(nessun utente umano trovato)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - ultima modifica effettuata da [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Messaggio di avviso del Robot: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Aggiunto sommario della discussione: %(num)i edit',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Aggiunto sommario della discussione con ripulitura: %(num)i edit',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Aggiornato sommario della discussione: %(num)i edit in %(page)s',
	},
	# Author: Fryed-peach
	'ja': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'議論に変更',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'議論終了',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'ロボットのメッセージ',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'新規議論',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'通知',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - %(user)sによる[%(history_link)s 最新の編集] (%(page_size)sバイト) (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s すべての議論が終わりました (監視停止) - %(user)sによる最新の編集 (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nボットによる出力: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(人間の編集者はみつかりませんでした)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u'* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - [[User:%(user)s]]による最新の編集 (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %Y-%m-%d',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* ロボットによる警告メッセージ: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'議論の要約の追加: %(num)i件',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'議論の要約の追加および除去: %(num)i件',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'ロボット',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'議論の要約の更新: %(page)sで%(num)i件',
	},
	# Author: Purodha
	'ksh': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'De Diskußjuhn wood verändert.',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Dä Klaaf es vörbei.',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'<span style="text-transform:uppercase">Nohreesch vum Bot: </span>',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Ene neue Klaaf',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Meddeilong',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s de letzte Änderong] (%(page_size)s Bytes) vum %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s alle Diskußjuhne sin eröm (Mer han mem Oppasse opjehüert) - de letzte Änderong es vum %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nZusammefaßong vum: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(Keine Minsch als Beärbeider jefonge)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - de letzte Änderong vum [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Bot-Warnonge: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'En Zosammefassong vun dä Diskußjuhn wood aanjeföösch: %(num)i Enndrääsch.',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'En Zosammefassong vun dä Diskußjuhn wood aanjeföösch un opjerühmp: %(num)i Enndrääsch.',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'Bot:',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'De Zosammefassong vun dä Diskußjuhn wood op ene neue Schtand jebraat: %(num)i Enndrääsch en dä Sigg %(page)s',
	},
	# Author: Robby
	'lb': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Diskussioun geännert',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Diskussioun ofgeschloss',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'Message vun engem Bot',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nei Diskussioun',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Matdeelung',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s lescht Ännerung] (%(page_size)s Byten) vum %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s alle Diskussiounen si fäerdeg (Iwwerwaachung gestoppt) - lescht Ännerung vum %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nResumé generéiert vun an ëm: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(kee mënschlechen Auteur fonnt)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - lescht Ännerung vum [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Bot Warn-Messagen: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Resumé vun der Diskussioun derbäigesat: %(num)i Entréeën',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Diskussioun: Resumé derbäigesat an Inhalt gekierzt (%(num)i Entréeën)',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'Bot:',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Resumé vun der Diskussioun aktualiséiert: %(num)i Entréeën op %(page)s',
	},
	# Author: Eitvys200
	'lt': {
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Diskusija uždaryta',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'ROBOTO PRANEŠIMAS',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robotas',
	},
	# Author: Papuass
	'lv': {
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robots',
	},
	# Author: StefanusRA
	'map-bms': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Dhiskusi diowahi',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Dhiskusi ditutup',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'PESENE BOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Dhiskusi Anyar',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notifikasi',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s bar diedit] (%(page_size)s bita) nang %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s kabeh dhiskusi wis rampung (\'\'surveillance stopped\'\') - sing nyunting keri dhewek yakuwe %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nSummary generated from and at: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(ora nemokna editor menungsa)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - sing nyunting keri dhewek yakuwe [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Pesen pengetan Bot: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Kesimpulan dhiskusi ditambahna: %(num)i entri',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Discussion summary added with clean up: %(num)i entries',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Ringkesane dhiskusi dimutakhirna: %(num)i entri nang %(page)s',
	},
	# Author: Jagwar
	'mg': {
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(tsy nahitana olombelona manova)',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'rôbô',
	},
	# Author: Bjankuloski06
	# Author: DrTrigon
	# Author: Rancher
	'mk': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'замена на ознака/ки %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Разговорот е изменет',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Разговорот е затворен',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'БОТОВСКА ПОРАКА',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Нов разговор',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Известување',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s последно уредување] (%(page_size)s бајти) од %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s сите разговори се завршени (надзорот е прекинат) - последното уредување го извршил %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nОписот е срочен од и на: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(не е пронајден човечки уредник)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - последното уредување го извршил [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Предупредување од роботот: %(page)s „\'\'%(warning)s\'\'“',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Додаден опис на разговорот: %(num)i записи',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Додаден опис на разговорот со чистењети: %(num)i записи',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'робот',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Описот на разговорот е изменет: %(num)i записи во %(page)s',
	},
	# Author: Kaajawa
	'mr': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'चर्चेत बदल',
	},
	# Author: Anakmalaysia
	# Author: DrTrigon
	'ms': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'menggantikan tag %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Perbincangan diubah',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Perbincangan ditutup',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'PESANAN BOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Perbincangan Baru',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Pemberitahuan',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s suntingan terakhir] (%(page_size)s bait) oleh %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s, semua perbincangan telah diselesaikan (pengawasan dihentikan) - suntingan terakhir oleh %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nRingkasan dijana dari dan di: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(tiada penyunting manusia dijumpai)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - suntingan terakhir oleh [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Pesanan amaran bot: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Ringkasan perbincangan baru: %(num)i entri',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Ringkasan perbincangan baru dengan pengemasan: %(num)i entri',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Ringkasan perbincangan dikemas kini: %(num)i entri di %(page)s',
	},
	'no': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Diskusjon endret',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Diskusjon stengt',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'BOTMELDING',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Ny diskusjon',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Varsel',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_section)s – [%(history_link)s siste endring] (%(page_size)s byte) av %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s alle diskusjoner er ferdige (overvåkning stoppet) – siste endring av %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nSammendrag generert fra og på: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(ingen menneskelig bidragsyter funnet)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> – siste endring av [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %Y-%m-%d',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Botadvarsel: %(page)s «\'\'%(warning)s\'\'»',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Diskusjonssammendrag lagt til: %(num)i oppføringer',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Diskusjonssammendrag lagt til med opprydning: %(num)i oppføringer',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Diskusjonssammendrag oppdatert: %(num)i oppføringer i %(page)s',
	},
	# Author: Servien
	'nds-nl': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Overleg ewiezigd',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Overleg esleuten',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'BOTBERICHT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Niej overleg',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Melding',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s leste bewarking] (%(page_size)s bytes) deur %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s alle overleggen bin aoferund (bewaking stop-ezet) - leste bewarking deur %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nSamenvatting emaakt van en op: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(gien meenselike redakteur evunnen)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - leste bewarking deur [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Botwaorschuwing: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Overlegsamenvatting derbie ezet: %(num)i regels',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Overlegsamenvatting derbie ezet, inklusief ankeren: %(num)i regels',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Overlegsamenvatting bie-ewörken: %(num)i regels in pagina %(page)s',
	},
	# Author: SPQRobin
	# Author: Siebrand
	# Author: DrTrigon
	'nl': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'substitutie van label(s) %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Overleg gewijzigd',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Overleg gesloten',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'ROBOTBERICHT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nieuw overleg',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Melding',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s laatste bewerking] (%(page_size)s bytes) door %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s alle overleggen zijn afgerond (bewaking gestopt) - laatste bewerking door %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nSamenvatting gemaakt van en op: %s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(geen menselijke redacteur gevonden)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - laatste bewerking door [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Robotwaarschuwing: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Overlegsamenvatting toegevoegd: %(num)i regels',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Overlegsamenvatting toegevoegd, inclusief opruimen: %(num)i regels',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Overlegsamenvatting bijgewerkt: %(num)i regels in pagina %(page)s',
	},
	# Author: Xqt
	'pdc': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Dischbedutt geennert',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s Gebeschdl] (%(page_size)s Beit) vun %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'\nWaddefresser',
	},
	# Author: Sp5uhe
	# Author: DrTrigon
	# Author: BeginaFelicysym
	'pl': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'zastępowanie %(tags)s znaczników',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Zmiana w dyskusji',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Dyskusja zakończona',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'KOMUNIKAT ROBOTA',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nowa dyskusja',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Powiadomienie',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s – %(page_sections)s – [%(history_link)s ostatnia zmiana] (%(page_size)s bajtów) %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s – na %(page)s zakończono wszystkie dyskusje (monitorowanie zatrzymane) – ostatnia zmiana %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nPodsumowanie wygenerowane z i na %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(nie odnaleziono żadnego autora, który byłby człowiekiem)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s – <span class="plainlinks">[%(page_link)s %(page)s]</span> – ostatnia zmiana [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %Y-%m-%d %B',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Robot ostrzega – %(page)s „\'\'%(warning)s\'\'“',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Dodane podsumowanie dyskusji: %(num)i wpisów',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Dodano podsumowanie dyskusji z wyczyszczeniem %(num)i wpisów',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Zaktualizowano podsumowanie dyskusji %(num)i wpisów na %(page)s',
	},
	# Author: Dragonòt
	# Author: Borichèt
	'pms': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'sustituì %(tags)s tag(s)',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discussion cangià',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discussion sarà',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MËSSAGI ËD TRIGOMIRO',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Discussion Neuva',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notìfica',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s ùltima modìfica] (%(page_size)s byte) da %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s tute le discussion a son finìe (dzorvejansa finìa) - ùltima modìfica da %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nResumé generà da e a: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(pa gnun editor uman trovà)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - ùltima modìfica da [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Mëssagi d\'avis dël trigomiro: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Giontà resumé dla discussion: %(num)i vos',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Giontà somari dla discussion con polissìa: %(num)i vos',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'trigomiro',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Modificà somari dla discussion: %(num)i vos an %(page)s',
	},
	# Author: Giro720
	# Author: DrTrigon
	'pt': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discussão alterada',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discussão encerrada',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MENSAGEM DO ROBÔ',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nova discussão',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notificação',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s última modificação] (%(page_size)s bytes) por %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s todas as discussões terminaram (vigilância parada) - última modificação por %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nResumo gerado a partir de e em: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(Nenhum editor humano encontrado)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - última modificação por [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Mensagem de aviso do robô: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Adicionado resumo da discussão: %(num)i entradas',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Resumo da discussão adicionado com limpeza: %(num)i entradas',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robô',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Atualizado o resumo da discussão: %(num)i entradas em %(page)s',
	},
	# Author: Pedroca cerebral
	# Author: Luigipiccoli
	'pt-br': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'substituindo %(tags)s tag(s)',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discussão alterada',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discussão encerrada',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MENSAGEM DO ROBÔ',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nova discussão',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notificação',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s última modificação] (%(page_size)s bytes) por %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s todas as discussões terminaram (vigilância parada) - última edição feita por %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nResumo gerado a partir de e em: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(Nenhum editor humano encontrado)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - última edição feita por [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Mensagem de aviso do robô: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Adicionado resumo da discussão: %(num)i entradas',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Resumo da discussão adicionado com limpeza: %(num)i entradas',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robô',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Atualizado o resumo da discussão: %(num)i entradas em %(page)s',
	},
	# Author: DrTrigon
	# Author: Siebrand
	# Author: EugeneZelenko
	# Author: McDutchie
	'qqq': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'Summary line (second part) if the page had to be modified due to new results. Parameters:\n* %(tags)s is a list of tag(s) updated on page',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'First part of message if discussion has changed.',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'First part of message if discussion was closed.',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'First part of message if it is a extraordinary maintenance message.\n\n(It\'s a system message that can only be triggered by the bot maintainer. Thus it\'s not important to translate the text.)',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'First part of message if discussion is new.',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'First part of message if it is a interwiki notification.\n{{Identical|Notification}}',
		'thirdparty-drtrigonbot-sum_disc-parse': u'Message for reporting of new or changed discussion pages (sections within pages).',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u'Message for reporting of closed discussion pages.',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'Message footer for bot report output.',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'Message part indicating the fact that no human editor is given for a page.',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u'Message for reporting of interwiki notifications.',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'Message header for bot report output. Is just a timestamp format and language independent.\n\nTimestamp format markers are as in the "strftime" C function. See "man 3 strftime" on any Linux/Unix system, or http://www.manpagez.com/man/3/strftime/',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u'Message for reporting of unexpected behaviour or situations to the user.',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Summary line second part if there are additional results.',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Summary line second part if there are additional results and old get removed.',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'Summary line first part.',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Summary line second part if the page had to be modified due to new results. Parameters:\n* %(num)i is the numer of entries\n* %(page)s is the page that was updated',
	},
	# Author: Minisarm
	# Author: Strainu
	'ro': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discuție modificată',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discuție închisă',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'MESAJ AUTOMAT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Discuție nouă',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notificare',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s ultima modificare] (%(page_size)s octeți) de %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\nRezumat generat din și la: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(nu s-a găsit un editor uman)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> – ultima modificare de [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Mesaj de avertizare de la robot: %(page)s „\'\'%(warning)s\'\'”',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
	},
	# Author: DrTrigon
	# Author: Rubin
	# Author: Express2000
	'ru': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'заменяются теги %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Обсуждение изменилось',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Обсуждение закрыто',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'СООБЩЕНИЕ РОБОТА',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Новое обсуждение',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Уведомление',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s последняя правка] (%(page_size)s байт) участником %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s все обсуждения закончены (наблюдение окончено) - последняя правка участника %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nРезюме составлено: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(участники-редакторы не найдены)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - последняя правка участника [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Предупреждение робота: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Резюме обсуждения добавлено: %(num)i записей',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Добавлен итог и скорректировано обсуждение: %(num)i записей',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'Робот',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Резюме обсуждения обновлено: %(num)i записей на %(page)s',
	},
	# Author: බිඟුවා
	# Author: පසිඳු කාවින්ද
	'si': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'සාකච්ඡාව වෙනස් කරන ලදී',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'සාකච්ඡාව හමාරයි',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'නව සාකච්ඡාව',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'නිවේදනය',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'රොබෝ',
	},
	# Author: Wizzard
	'sk': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Diskusia zmenená',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Diskusia zatvorená',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'SPRÁVA ROBOTA',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nová diskusia',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Upozornenie',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nZhrnutie vygenerované z a v: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(nebol nájdený žiadny ľudský redaktor)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
	},
	# Author: Dbc334
	# Author: DrTrigon
	'sl': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'zamenjevanje oznak %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Razprava je bila spremenjena',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Razprava je zaprta',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'SPOROČILO ROBOTA',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Nova razprava',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Obvestilo',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s – [%(history_link)s zadnje urejanje] (%(page_size)s bajtov) od %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s vse razprave so končane (ustavljam nadzor) – zadnje urejanje od %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nPovzetek ustvaril, dne: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(najden ni noben človeški urejevalec)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> – nazadnje urejal [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Opozorilno sporočilo robota: %(page)s »\'\'%(warning)s\'\'«',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Dodan povzetek razprave: %(num)i vnosov',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Dodan povzetek razprave s čiščenjem: %(num)i vnosov',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Posodobljen povzetek razprave: %(num)i vnosov na %(page)s',
	},
	# Author: DrTrigon
	# Author: Rancher
	'sr': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'замена ознака %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Разговор је измењен',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Разговор је затворен',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'РОБОТОВА ПОРУКА',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Нови разговор',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Обавештење',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s – [%(history_link)s последња измена] (%(page_size)s бајтова) од %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s сви разговори су завршени (надзор је прекинут) – последња измена од %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nОпис је створен из и у: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(нема уредника)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> – последња измена од [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Роботово упозорење: %(page)s „\'\'%(warning)s\'\'“',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Додат је опис разговора: %(num)i уноса',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Додат је опис разговора са чишћењем: %(num)i уноса',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'робот',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Опис разговора је ажуриран: %(num)i уноса у %(page)s',
	},
	# Author: Rancher
	# Author: DrTrigon
	'sr-el': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'zamena oznaka %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Razgovor je izmenjen',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Razgovor je zatvoren',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'ROBOTOVA PORUKA',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Novi razgovor',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Obaveštenje',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s – [%(history_link)s poslednja izmena] (%(page_size)s bajtova) od %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s svi razgovori su završeni (nadzor je prekinut) – poslednja izmena od %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nOpis je stvoren iz i u: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(nema urednika)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> – poslednja izmena od [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Robotovo upozorenje: %(page)s „\'\'%(warning)s\'\'“',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Dodat je opis razgovora: %(num)i unosa',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Dodat je opis razgovora sa čišćenjem: %(num)i unosa',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Opis razgovora je ažuriran: %(num)i unosa u %(page)s',
	},
	# Author: WikiPhoenix
	'sv': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Diskussion ändrad',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Diskussion stängt',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'BOTMEDDELANDE',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Ny diskussion',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Meddelande',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s senaste redigering] (%(page_size)s byte) av %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s alla diskussioner är klara (övervakning stoppades) - senaste redigering av %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nSammanfattning genererades från och på: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(inga mänskliga redigerare hittades)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - senaste redigering av [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u': * Botvarningsmeddelande: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Diskussionssammanfattning lades till: %(num)i poster',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Diskussionssammanfattning lades till med resning : %(num)i poster',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Diskussionssammanfattning uppdaterades: % %(num)i poster i %(page)s',
	},
	# Author: Shanmugamp7
	'ta': {
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(மனித திருத்தி காணப்படவில்லை)',
	},
	# Author: Гусейн
	'tly': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Мызокирә дәгиш быә',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Мызокирә бастә быә',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'РОБОТИ ХӘБӘ',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Нуә Мызокирә',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Хәбәдо',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s охонә дәгиш] (%(page_size)s бајт) иштирокәкә %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s һәммәј мызокирон орохәјн (тәмшо орохәј) - иштирокәкәси охонә дәгиш %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nСәкыштә сохтә быә: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(иштирокәкәсон-редәкторон пәјдо кардә бәнин)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - иштирокәкәси охонә дәгиш [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Роботи чәшнави кардеј: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Мызокирә сәкыштә зијод кардә быә: %(num)i нывыштәјон',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Сәкыштә зијод кардә быә ијән сәрост кардә быә мызокирә: %(num)i нывыштәјон',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'робот',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Мызокирә сәкыштә нуә кардә быә: %(num)i нывыштәјон бә %(page)s',
	},
	# Author: Khutuck
	# Author: Emperyan
	'tr': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Tartışma değiştirildi.',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Tartışma kapandı.',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'ROBOT İLETİ',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Yeni Tartışma',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Bilgilendirme',
		'thirdparty-drtrigonbot-sum_disc-parse': u'Bot:* %(notify)s: %(page_sections)s - [%(history_link)s son değişiklik] (%(page_size)s byte) kullanıcı %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s tüm tartışmalar sona erdi (izleme sonlandırıldı) - son değişiklik %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nÖzet hazırlandı: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(insan editör bulunamadı)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - son değişiklik [[Kullanıcı:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Robot uyarı iletisi: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Tartışma özeti eklendi: %(num)i bilgi.',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Tartışma özeti eklendi ve düzenlendi: %(num)i bilgi.',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'Bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Tartışma özeti güncellendi: %(page)s sayfada %(num)i bilgi.',
	},
	# Author: Dim Grits
	'uk': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Обговорення зазнало нових змін',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Обговорення закрито',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'ROBOT MESSAGE',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Нове обговорення',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Сповіщення',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s остання правка] (%(page_size)s байт) користувачем %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s усі обговорення завершено (спостереження завершено) - остання правка коритсувача %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nРезюме складене: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(людини-редактора не знайдено)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> - остання правка користувача [[User:%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Попередження бота: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'До резюме обговорення додано: %(num)i записів',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'До резюме обговорення додано і підчищено: %(num)i записів',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'бот',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Резюме обговорення оновлено: %(num)i записів на %(page)s',
	},
	# Author: Minh Nguyen
	# Author: DrTrigon
	'vi': {
		'thirdparty-drtrigonbot-subster-summary-mod': u'thay thế các thẻ %(tags)s',
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Thảo luận đã được thay đổi',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Thảo luận đã kết thúc',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'THÔNG ĐIỆP BOT',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'Thảo luận mới',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Thông báo',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s – [%(history_link)s sửa đổi cuối cùng] (%(page_size)s byte) bởi %(user)s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s – mọi thảo luận đã kết thúc (ngừng theo dõi) – sửa đổi lần cuối cùng bởi [[User:%(user)s|%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nThành viên và lúc giờ tính tóm lược: %(sign)s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(không tìm thấy người thật sửa đổi)',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span> – sửa đổi lần cuối cùng bởi [[User:%(user)s|%(user)s]] (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Bot cảnh báo: %(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'Đã thêm tóm lược thảo luận: %(num)i mục',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Đã thêm tóm lược thảo luận và dọn dẹp: %(num)i mục',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'bot',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Đã cập nhật tóm lược thảo luận: %(num)i mục tại “%(page)s”',
	},
	# Author: פוילישער
	'yi': {
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'באט',
	},
	# Author: Anakmalaysia
	'zh': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'讨论改变',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'讨论关闭',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'机器人的消息',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'新讨论',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'通知',
		'thirdparty-drtrigonbot-sum_disc-parse': u':* %(notify)s: %(page_sections)s - [%(history_link)s 最近编辑]（%(page_size)s字节）由%(user)s作出（%(time)s）',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %(notify)s: %(page)s所有讨论已完成（停止监测）——最近编辑由[[User:%(user)s]]作出（%(time)s）',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\n摘要由在%(sign)s生成</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'（找不到人类编辑者）',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %(notify)s: <span class="plainlinks">[%(page_link)s %(page)s]</span>——最近编辑由[[User:%(user)s]]作出（%(time)s）',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %Y %B %d.',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* 机器人警告消息：%(page)s "\'\'%(warning)s\'\'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'添加讨论摘要：%(num)i个条目',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'添加讨论摘要及清理：%(num)i个条目',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'机器人',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'更新讨论摘要：%(num)i个条目在%(page)s',
	},
	# Author: Breawycker
	'zh-hant': {
		'thirdparty-drtrigonbot-sum_disc-notify-changed': u'更改的討論',
		'thirdparty-drtrigonbot-sum_disc-notify-closed': u'關閉的討論',
		'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'機器人消息',
		'thirdparty-drtrigonbot-sum_disc-notify-new': u'檢視討論頁面',
		'thirdparty-drtrigonbot-sum_disc-notify-notify': u'通知',
		'thirdparty-drtrigonbot-sum_disc-parse': u'： ＊ %（通知） s: (page_sections) %s-[%（history_link） s 最後編輯] （（page_size） %s 的位元組） （使用者） %s (%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-closed': u'： ＊ %（通知） （使用者） %s (%(time)s) 通過最後編輯所有討論都完 (監察停止）--s: %（頁） s',
		'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n!N ！從和在生成的摘要： （符號） %s</noinclude>',
		'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'（沒有發現人類編輯器）',
		'thirdparty-drtrigonbot-sum_disc-parse-notify': u'： ＊ %（通知） s: <span class="plainlinks">[(page_link) 的 （頁） s]</span> -[[（使用者） 使用者： %s]] 通過最後編輯 （%(time)s)',
		'thirdparty-drtrigonbot-sum_disc-parse-start': u';%d. %B %Y',
		'thirdparty-drtrigonbot-sum_disc-parse-warning': u'： ＊ 機器人警告消息： （頁） %s"%（警告） s \'"',
		'thirdparty-drtrigonbot-sum_disc-summary-add': u'添加的討論摘要： %(num) 我的條目',
		'thirdparty-drtrigonbot-sum_disc-summary-clean': u'添加具有清理的討論摘要： %(num) 我的條目',
		'thirdparty-drtrigonbot-sum_disc-summary-head': u'機器人',
		'thirdparty-drtrigonbot-sum_disc-summary-mod': u'討論摘要更新： %(num) 我 （頁） %s 中的條目',
	},
}
