# coding=utf-8
msg = {
        'en': {
                'thirdparty-drtrigonbot-sum_disc-summary-head': u'robot ',
                'thirdparty-drtrigonbot-sum_disc-summary-add': u'Discussion summary added: %i entries',
                'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Discussion summary updated: %i entries in %s',
                'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Discussion summary added with clean up: %i entries',
                'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Discussion changed',
                'thirdparty-drtrigonbot-sum_disc-notify-new': u'New Discussion',
                'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Discussion closed',
                'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'BOT MESSAGE',
                'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Notification',
                'thirdparty-drtrigonbot-sum_disc-parse': u':* %s: %s - [%s last edit] ({{PAGESIZE:%s}} bytes) by %s (%s)',
                'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %s: %s all discussions have finished (surveillance stopped) - last edit by %s (%s)',
                'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %s: <span class="plainlinks">[%s %s]</span> - last edit by [[User:%s]] (%s)',
                'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Bot warning message: %s "\'\'%s\'\'"',
                'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
                'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nSummary generated from and at: %s</noinclude>',
                'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(no human editor found)',
        },
        'de': {
                'thirdparty-drtrigonbot-sum_disc-summary-head': u'Bot: ',
                'thirdparty-drtrigonbot-sum_disc-summary-add': u'Diskussions-Zusammenfassung hinzugefügt (%i Einträge)',
                'thirdparty-drtrigonbot-sum_disc-summary-mod': u'Diskussions-Zusammenfassung aktualisiert (%i Einträge in %s)',
                'thirdparty-drtrigonbot-sum_disc-summary-clean': u'Diskussions-Zusammenfassung hinzugefügt und bereinigt (%i Einträge)',
                'thirdparty-drtrigonbot-sum_disc-notify-changed': u'Diskussion verändert',
                'thirdparty-drtrigonbot-sum_disc-notify-new': u'Neue Diskussion',
                'thirdparty-drtrigonbot-sum_disc-notify-closed': u'Diskussion abgeschlossen',
                'thirdparty-drtrigonbot-sum_disc-notify-maintmsg': u'BOT MESSAGE',
                'thirdparty-drtrigonbot-sum_disc-notify-notify': u'Benachrichtigung',
                'thirdparty-drtrigonbot-sum_disc-parse': u':* %s: %s - [%s letzte Bearbeitung] ({{PAGESIZE:%s}} Bytes) von %s (%s)',
                'thirdparty-drtrigonbot-sum_disc-parse-closed': u':* %s: %s alle Diskussionen wurden beendet (Überwachung gestoppt) - letzte Bearbeitung von %s (%s)',
                'thirdparty-drtrigonbot-sum_disc-parse-notify': u':* %s: <span class="plainlinks">[%s %s]</span> - letzte Bearbeitung von [[User:%s]] (%s)',
                'thirdparty-drtrigonbot-sum_disc-parse-warning': u':* Bot Warn-Nachricht: %s "\'\'%s\'\'"',
                'thirdparty-drtrigonbot-sum_disc-parse-start': u'; %d. %B %Y',
                'thirdparty-drtrigonbot-sum_disc-parse-end': u'<noinclude>\n\nZusammenfassung erstellt von und um: %s</noinclude>',
                'thirdparty-drtrigonbot-sum_disc-parse-nonhuman': u'(keinen menschlichen Bearbeiter gefunden)',
        },
}

