[tox]
minversion = 3.21
skipsdist = True
skip_missing_interpreters = True
envlist =
    lint-py{310,313}

[testenv]
basepython =
    py310: python3.10
    py313: python3.13
setenv =
    VIRTUAL_ENV={envdir}
    PRE_COMMIT_COLOR=always
deps =
    pre-commit >= 4.2.0
commands =
    python --version
    pre-commit run --all-files --show-diff-on-failure
    pre-commit gc
