#  -*-  coding:  utf-8  -*-
msg = {
        'nl': {
                'wiktionary-lang-translingual': u'Taalonafhankelijk',
                'wiktionary-lang-nl': u'Nederlands',
                'wiktionary-lang-en': u'Engels',
                'wiktionary-lang-de': u'Duits',
                'wiktionary-lang-fr': u'Frans',
                'wiktionary-lang-it': u'Italiaans',
                'wiktionary-lang-eo': u'Esperanto',
                'wiktionary-lang-es': u'Spaans',
        },
        'de': {
                'wiktionary-lang-nl': u'Niederländisch',
                'wiktionary-lang-en': u'Englisch',
                'wiktionary-lang-de': u'Deutsch',
                'wiktionary-lang-fr': u'Französisch',
                'wiktionary-lang-it': u'Italienisch',
                'wiktionary-lang-eo': u'Esperanto',
                'wiktionary-lang-es': u'Spanisch',
        },
        'en': {
                'wiktionary-lang-translingual': u'Translingual',
                'wiktionary-lang-nl': u'Dutch',
                'wiktionary-lang-en': u'English',
                'wiktionary-lang-de': u'German',
                'wiktionary-lang-fr': u'French',
                'wiktionary-lang-it': u'Italian',
                'wiktionary-lang-eo': u'Esperanto',
                'wiktionary-lang-es': u'Spanish',
        },
        'eo': {
                'wiktionary-lang-nl': u'Nederlanda',
                'wiktionary-lang-en': u'Angla',
                'wiktionary-lang-de': u'Germana',
                'wiktionary-lang-fr': u'Franca',
                'wiktionary-lang-it': u'Italiana',
                'wiktionary-lang-eo': u'Esperanto',
                'wiktionary-lang-es': u'Hispana',
        },
        'ia': {
                'wiktionary-lang-translingual': u'translingual',
                'wiktionary-lang-nl': u'nederlandese',
                'wiktionary-lang-en': u'anglese',
                'wiktionary-lang-de': u'germano',
                'wiktionary-lang-fr': u'francese',
                'wiktionary-lang-it': u'italiano',
                'wiktionary-lang-eo': u'esperanto',
                'wiktionary-lang-es': u'espaniol',
        },
        'it': {
                'wiktionary-lang-nl': u'olandese',
                'wiktionary-lang-en': u'inglese',
                'wiktionary-lang-de': u'tedesco',
                'wiktionary-lang-fr': u'francese',
                'wiktionary-lang-it': u'italiano',
                'wiktionary-lang-eo': u'esperanto',
                'wiktionary-lang-es': u'spagnuolo',
        },
        'fr': {
                'wiktionary-lang-nl': u'néerlandais',
                'wiktionary-lang-en': u'anglais',
                'wiktionary-lang-de': u'allemand',
                'wiktionary-lang-fr': u'français',
                'wiktionary-lang-it': u'italien',
                'wiktionary-lang-eo': u'espéranto',
                'wiktionary-lang-es': u'espagnol',
        },
        'es': {
                'wiktionary-lang-nl': u'olandés',
                'wiktionary-lang-en': u'inglés',
                'wiktionary-lang-de': u'alemán',
                'wiktionary-lang-fr': u'francés',
                'wiktionary-lang-it': u'italiano',
                'wiktionary-lang-eo': u'esperanto',
                'wiktionary-lang-es': u'español',
        },
        'sr': {
                'wiktionary-lang-translingual': u'Вишејезички',
                'wiktionary-lang-nl': u'холандски',
                'wiktionary-lang-en': u'енглески',
                'wiktionary-lang-de': u'немачки',
                'wiktionary-lang-fr': u'француски',
                'wiktionary-lang-it': u'италијански',
                'wiktionary-lang-eo': u'есперанто',
                'wiktionary-lang-es': u'шпански',
        },
}
